using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using AvroSharp.Schemas;

namespace AvroSharp.CodeGen;

/// <summary>
/// Generates C# types for the named types (records, enums and fixed types) of Avro schemas. Each record gets static
/// <c>Write</c>/<c>Read</c> methods that call <c>AvroWriter</c>/<c>AvroReader</c> directly, in schema order.
/// </summary>
/// <remarks>Output is deterministic: the same schemas and options always produce the same files, in the same order.</remarks>
public static class CSharpCodeGenerator
{
    private const string Tool = "AvroSharp.CodeGen";

    /// <summary>Generates one source file per named type reachable from <paramref name="schemas"/>.</summary>
    /// <param name="schemas">The schemas. A named type reachable from several of them is generated once.</param>
    /// <param name="options">Options, or <see langword="null"/> for <see cref="CodeGenOptions.Default"/>.</param>
    public static IReadOnlyList<GeneratedSource> Generate(IEnumerable<AvroSchema> schemas, CodeGenOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(schemas);
        options ??= CodeGenOptions.Default;
        var names = new CSharpNames(options);
        var types = new TypeMapper(names, options);

        var named = new SortedDictionary<string, NamedSchema>(StringComparer.Ordinal);
        foreach (var schema in schemas)
        {
            Collect(schema, named);
        }

        var version = typeof(CSharpCodeGenerator).Assembly.GetName().Version?.ToString() ?? "0.0.0.0";
        var apache = options.ApacheCompatible;
        var sources = named.Values.Select(schema => new GeneratedSource(schema.FullName + ".g.cs", Emit(schema, names, types, version, apache))).ToList();
        if (apache)
        {
            sources.Add(new GeneratedSource(ApacheSupport.HintName, ApacheSupport.Source(version, options.NullableAnnotations)));
        }

        return sources;
    }

    private static void Collect(AvroSchema schema, SortedDictionary<string, NamedSchema> named)
    {
        switch (schema)
        {
            case NamedSchema namedSchema when named.ContainsKey(namedSchema.FullName):
                return;
            case RecordSchema record:
                named.Add(record.FullName, record);
                foreach (var field in record.Fields)
                {
                    Collect(field.Schema, named);
                }

                break;
            case NamedSchema namedSchema:
                named.Add(namedSchema.FullName, namedSchema);
                break;
            case ArraySchema array:
                Collect(array.Items, named);
                break;
            case MapSchema map:
                Collect(map.Values, named);
                break;
            case UnionSchema union:
                foreach (var branch in union.Branches)
                {
                    Collect(branch, named);
                }

                break;
        }
    }

    private static string Emit(NamedSchema schema, CSharpNames names, TypeMapper types, string version, bool apache)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line($"// Generated by {Tool} from the Avro schema of '{schema.FullName}'. Do not edit.");
        if (types.Annotations)
        {
            w.Line("#nullable enable");
        }

        w.Line("#pragma warning disable CS1591 // Members without an Avro doc have no documentation comment.");
        w.Line();

        var ns = names.Namespace(schema);
        if (ns is not null)
        {
            w.Open($"namespace {ns}");
        }

        Doc(w, schema.Doc);
        w.Line($"[global::System.CodeDom.Compiler.GeneratedCode({CSharpNames.Literal(Tool)}, {CSharpNames.Literal(version)})]");
        var name = CSharpNames.Identifier(schema.Name.Name);
        switch (schema)
        {
            case RecordSchema record:
                EmitRecord(w, record, name, names, types, apache);
                break;
            case EnumSchema enumSchema:
                EmitEnum(w, enumSchema, name);
                break;
            case FixedSchema fixedSchema:
                EmitFixed(w, fixedSchema, name, apache, types);
                break;
        }

        if (ns is not null)
        {
            w.Close();
        }

        return w.ToString();
    }

    private const string Writer = "global::AvroSharp.IO.AvroWriter";
    private const string Reader = "global::AvroSharp.IO.AvroReader";
    private const string Support = "global::AvroSharp.Serialization.AvroGeneratedCode";

    private static void EmitRecord(CodeWriter w, RecordSchema record, string name, CSharpNames names, TypeMapper types, bool apache)
    {
        var properties = PropertyNames(record, name, types.Naming);
        w.Open($"public sealed partial class {name} : global::AvroSharp.Serialization.IAvroSpecificRecord{(apache ? ", " + ApacheSupport.SpecificRecord : string.Empty)}");
        EmitSchemaMembers(w, record, "Schema", apache, types);

        for (var i = 0; i < record.Fields.Count; i++)
        {
            var field = record.Fields[i];
            w.Line();
            Doc(w, field.Doc);
            var initializer = types.Initializer(field.Schema);
            w.Line($"public {types.TypeOf(field.Schema)} {properties[i]} {{ get; set; }}{(initializer is null ? string.Empty : " = " + initializer + ";")}");
        }

        EmitRecordApi(w, name);
        EmitRecordAccess(w, record, properties, types, apache);
        if (apache)
        {
            ApacheSupport.EmitRecordMembers(w, types);
        }

        EmitRecordCore(w, record, name, properties, new SerializerEmitter(names, types));
        w.Close();
    }

    /// <summary>The public entry points; they delegate to the depth-tracking cores.</summary>
    private static void EmitRecordApi(CodeWriter w, string name)
    {
        w.Line();
        w.Line("/// <summary>Writes a value in Avro binary encoding.</summary>");
        w.Open($"public static void Write(ref {Writer} writer, {name} value)");
        w.Open("if (value is null)");
        w.Line("throw new global::System.ArgumentNullException(nameof(value));");
        w.Close();
        w.Line();
        w.Line("WriteCore(ref writer, value, 0);");
        w.Close();

        w.Line();
        w.Line("/// <summary>Reads a value written with this type's schema.</summary>");
        w.Line($"public static {name} Read(ref {Reader} reader) => ReadCore(ref reader, 0);");

        w.Line();
        w.Line("/// <summary>Writes this value to a new array, in Avro binary encoding.</summary>");
        w.Line($"public byte[] ToAvroBytes() => {Support}.SerializeToArray(this, Write);");

        w.Line();
        w.Line("/// <summary>Reads a value from Avro binary data written with this type's schema.</summary>");
        w.Open($"public static {name} FromAvroBytes(global::System.ReadOnlySpan<byte> data)");
        w.Line($"var reader = new {Reader}(data);");
        w.Line("return ReadCore(ref reader, 0);");
        w.Close();

        EmitResolvingApi(w, name);
    }

    /// <summary>
    /// Schema resolution: data of another version of the schema is read by the pair's plan, or resolved to this type's
    /// schema first when the writer schema is not a record of the same name.
    /// </summary>
    private static void EmitResolvingApi(CodeWriter w, string name)
    {
        w.Line();
        w.Line("/// <summary>");
        w.Line("/// Reads a value written with <paramref name=\"writerSchema\"/>, another version of this type's schema, resolving the");
        w.Line("/// differences as the specification allows (added fields take their defaults, removed fields are skipped, numbers");
        w.Line("/// are promoted). Data written with this type's own schema is read directly.");
        w.Line("/// </summary>");
        w.Open($"public static {name} Read(ref {Reader} reader, global::AvroSharp.Schemas.AvroSchema writerSchema)");
        w.Open($"if ({Support}.IsSameSchema(writerSchema, Schema))");
        w.Line("return ReadCore(ref reader, 0);");
        w.Close();
        w.Line();
        w.Line($"var plan = {Support}.GetRecordPlan(writerSchema, Schema);");
        w.Open("if (plan != null)");
        w.Line("return ReadResolved(ref reader, plan, 0);");
        w.Close();
        w.Line();
        w.Line($"return FromAvroBytes({Support}.ResolveToReaderEncoding(ref reader, writerSchema, Schema));");
        w.Close();

        w.Line();
        w.Line("/// <summary>Reads a value from Avro binary data written with <paramref name=\"writerSchema\"/>, resolving schema differences.</summary>");
        w.Open($"public static {name} FromAvroBytes(global::System.ReadOnlySpan<byte> data, global::AvroSharp.Schemas.AvroSchema writerSchema)");
        w.Line($"var reader = new {Reader}(data);");
        w.Line("return Read(ref reader, writerSchema);");
        w.Close();
    }

    /// <summary>
    /// <c>IAvroSpecificRecord</c>: field access by position, like Apache.Avro's <c>ISpecificRecord</c>. <c>Put</c> checks
    /// the value's type and names the field in its error. Uses only C# 7.3 syntax.
    /// </summary>
    private static void EmitRecordAccess(CodeWriter w, RecordSchema record, string[] properties, TypeMapper types, bool apache)
    {
        const string Interface = "global::AvroSharp.Serialization.IAvroSpecificRecord";
        var count = record.Fields.Count.ToString(CultureInfo.InvariantCulture);
        var invalid = $"throw {Support}.InvalidFieldPosition(fieldPos, {count}, {CSharpNames.Literal(record.FullName)});";

        w.Line();
        w.Line($"global::AvroSharp.Schemas.RecordSchema {Interface}.Schema => (global::AvroSharp.Schemas.RecordSchema)Schema;");

        w.Line();
        w.Line("/// <summary>Gets the value of the field at a position in the schema, boxed.</summary>");
        w.Open($"public {types.Nullable("object")} Get(int fieldPos)");
        w.Open("switch (fieldPos)");
        for (var i = 0; i < properties.Length; i++)
        {
            w.Line($"case {i.ToString(CultureInfo.InvariantCulture)}:");
            w.Indent();
            w.Line($"return this.{properties[i]};");
            w.Outdent();
        }

        w.Line("default:");
        w.Indent();
        w.Line(invalid);
        w.Outdent();
        w.Close();
        w.Close();

        w.Line();
        w.Line("/// <summary>Sets the value of the field at a position in the schema; the value must have the field's C# type.</summary>");
        w.Open($"public void Put(int fieldPos, {types.Nullable("object")} fieldValue)");
        w.Open("switch (fieldPos)");
        for (var i = 0; i < properties.Length; i++)
        {
            var field = record.FullName + "." + record.Fields[i].Name;
            w.Line($"case {i.ToString(CultureInfo.InvariantCulture)}:");
            w.Indent();
            w.Line($"this.{properties[i]} = {PutValue(record.Fields[i].Schema, types, field, "v" + i.ToString(CultureInfo.InvariantCulture), apache)};");
            w.Line("break;");
            w.Outdent();
        }

        w.Line("default:");
        w.Indent();
        w.Line(invalid);
        w.Outdent();
        w.Close();
        w.Close();
    }

    /// <summary>The expression that converts <c>fieldValue</c> to a field's type, or throws naming the field.</summary>
    private static string PutValue(AvroSchema schema, TypeMapper types, string field, string variable, bool apache)
    {
        var nullable = false;
        if (schema is UnionSchema union)
        {
            var (nullIndex, others) = TypeMapper.Classify(union);
            if (others.Count != 1)
            {
                // object?: any value; the union branch is checked when writing.
                return "fieldValue";
            }

            nullable = nullIndex >= 0;
            schema = union.Branches[others[0]];
        }
        else if (schema.Type == AvroSchemaType.Null)
        {
            return "fieldValue";
        }

        var type = types.TypeOf(schema);
        var display = type.Replace("global::", string.Empty) + (nullable ? "?" : string.Empty);
        var mismatch = $"throw {Support}.PutTypeMismatch(fieldValue, {CSharpNames.Literal(field)}, {CSharpNames.Literal(display)})";
        var converted = types.IsValueType(schema)
            ? $"fieldValue is {type} {variable} ? {variable} : {mismatch}"
            : $"fieldValue as {type} ?? {mismatch}";
        if (apache && schema is EnumSchema)
        {
            // Apache's specific reader puts an enum as its ordinal (a boxed int); its own generated code unboxes it.
            converted = $"fieldValue is {type} {variable} ? {variable} : fieldValue is int {variable}o ? ({type}){variable}o : {mismatch}";
        }
        else if (apache && schema is FixedSchema { LogicalType: DecimalLogicalType dec } fixedDecimal)
        {
            // Apache's specific reader puts a decimal on fixed as an AvroDecimal, after reusing the current value as a
            // SpecificFixed. Accept both; the field keeps the fixed type.
            var scale = dec.Scale.ToString(CultureInfo.InvariantCulture);
            var size = fixedDecimal.Size.ToString(CultureInfo.InvariantCulture);
            converted = $"fieldValue is {type} {variable} ? {variable} : fieldValue is global::Avro.AvroDecimal {variable}d ? new {type}(global::AvroSharp.Generated.ApacheDecimals.FixedBytes({variable}d, {scale}, {size})) : {mismatch}";
        }
        return nullable
            ? $"fieldValue == null ? ({(types.IsValueType(schema) ? type + "?" : types.Nullable(type))})null : {converted}"
            : converted;
    }

    /// <summary>The serializers: each field in schema order, with the record depth checked on entry.</summary>
    private static void EmitRecordCore(CodeWriter w, RecordSchema record, string name, string[] properties, SerializerEmitter emitter)
    {
        w.Line();
        w.Open($"internal static void WriteCore(ref {Writer} writer, {name} value, int depth)");
        w.Open($"if (depth > {Support}.MaxDepth)");
        w.Line($"throw {Support}.WriteTooDeep();");
        w.Close();
        for (var i = 0; i < record.Fields.Count; i++)
        {
            w.Line();
            emitter.Write(w, record.Fields[i].Schema, "value." + properties[i], record.FullName + "." + record.Fields[i].Name);
        }

        w.Close();

        w.Line();
        w.Open($"internal static {name} ReadCore(ref {Reader} reader, int depth)");
        w.Open($"if (depth > {Support}.MaxDepth)");
        w.Line($"throw {Support}.ReadTooDeep();");
        w.Close();
        w.Line();
        w.Line($"var value = new {name}();");
        for (var i = 0; i < record.Fields.Count; i++)
        {
            emitter.Read(w, record.Fields[i].Schema, "value." + properties[i]);
        }

        w.Line("return value;");
        w.Close();

        EmitReadResolved(w, record, name, properties, emitter);
    }

    /// <summary>
    /// Reading data of another schema version by its plan: writer fields in the writer's order, each read into its
    /// reader property directly, promoted, remapped (enums) or, for other differences, transcoded and then read; the
    /// reader fields the writer lacks take their defaults.
    /// </summary>
    private static void EmitReadResolved(CodeWriter w, RecordSchema record, string name, string[] properties, SerializerEmitter emitter)
    {
        w.Line();
        w.Open($"internal static {name} ReadResolved(ref {Reader} reader, global::AvroSharp.Serialization.AvroRecordPlan plan, int depth)");
        w.Open($"if (depth > {Support}.MaxDepth)");
        w.Line($"throw {Support}.ReadTooDeep();");
        w.Close();
        w.Line();
        w.Line($"var value = new {name}();");
        if (record.Fields.Count == 0)
        {
            // Nothing to fill: skip whatever fields the writer has.
            w.Open("for (var step = 0; step < plan.StepCount; step++)");
            w.Line("plan.Skip(step, ref reader);");
            w.Close();
            w.Line();
            w.Line("return value;");
            w.Close();
            return;
        }

        w.Open("for (var step = 0; step < plan.StepCount; step++)");
        w.Open("switch (plan.Target(step))");
        for (var i = 0; i < record.Fields.Count; i++)
        {
            EmitResolvedFieldCase(w, i, "value." + properties[i], record.Fields[i].Schema, emitter);
        }

        w.Line("default:");
        w.Indent();
        w.Line("plan.Skip(step, ref reader);");
        w.Line("break;");
        w.Outdent();
        w.Close();
        w.Close();
        EmitResolvedDefaults(w, record, properties);
        w.Line();
        w.Line("return value;");
        w.Close();

        EmitResolvedFieldReaders(w, record, emitter);
    }

    // The reader fields the writer lacks, from the plan's encoded defaults.
    private static void EmitResolvedDefaults(CodeWriter w, RecordSchema record, string[] properties)
    {
        w.Line();
        w.Open("for (var index = 0; index < plan.DefaultCount; index++)");
        w.Line($"var field = new {Reader}(plan.DefaultValue(index));");
        w.Open("switch (plan.DefaultTarget(index))");
        for (var i = 0; i < record.Fields.Count; i++)
        {
            w.Line($"case {Int(i)}:");
            w.Indent();
            w.Line($"value.{properties[i]} = ReadResolvedField{Int(i)}(ref field, depth);");
            w.Line("break;");
            w.Outdent();
        }

        w.Close();
        w.Close();
    }

    // One reader per field, the same code as ReadCore's, for the plan's direct, transcoded and default values.
    private static void EmitResolvedFieldReaders(CodeWriter w, RecordSchema record, SerializerEmitter emitter)
    {
        for (var i = 0; i < record.Fields.Count; i++)
        {
            var type = emitter.TypeOf(record.Fields[i].Schema);
            w.Line();
            w.Open($"private static {type} ReadResolvedField{Int(i)}(ref {Reader} reader, int depth)");
            w.Line($"{type} result;");
            emitter.Read(w, record.Fields[i].Schema, "result");
            w.Line("return result;");
            w.Close();
        }
    }

    // The case for reader field i: read as is, with a conversion the field's type allows, or transcoded first.
    private static void EmitResolvedFieldCase(CodeWriter w, int i, string target, AvroSchema schema, SerializerEmitter emitter)
    {
        const string Conversion = "global::AvroSharp.Serialization.AvroConversion";
        w.Line($"case {Int(i)}:");
        w.Indent();
        w.Open("switch (plan.Conversion(step))");
        w.Line($"case {Conversion}.None:");
        w.Indent();
        w.Line($"{target} = ReadResolvedField{Int(i)}(ref reader, depth);");
        w.Line("break;");
        w.Outdent();
        foreach (var conversion in emitter.ResolvedConversions(schema))
        {
            w.Line($"case {Conversion}.{conversion}:");
            w.Indent();
            emitter.ReadConverted(w, schema, conversion, target);
            w.Line("break;");
            w.Outdent();
        }

        w.Line("default:");
        w.Indent();
        w.Open();
        w.Line($"var field = new {Reader}(plan.Transcode(step, ref reader));");
        w.Line($"{target} = ReadResolvedField{Int(i)}(ref field, depth);");
        w.Line("break;");
        w.Close();
        w.Outdent();
        w.Close();
        w.Line("break;");
        w.Outdent();
    }

    private static string Int(int value) => value.ToString(CultureInfo.InvariantCulture);

    private static void EmitEnum(CodeWriter w, EnumSchema schema, string name)
    {
        w.Open($"public enum {name}");
        for (var i = 0; i < schema.Symbols.Count; i++)
        {
            w.Line($"{CSharpNames.Identifier(schema.Symbols[i])} = {i.ToString(CultureInfo.InvariantCulture)},");
        }

        w.Close();
    }

    private static void EmitFixed(CodeWriter w, FixedSchema schema, string name, bool apache, TypeMapper types)
    {
        if (apache)
        {
            ApacheSupport.EmitFixed(w, schema, name, types, s => EmitSchemaMembers(w, s, "AvroSharpSchema", apache: true, types));
            return;
        }

        w.Open($"public sealed partial class {name} : global::System.IEquatable<{name}>");
        w.Line("/// <summary>The number of bytes in a value.</summary>");
        w.Line($"public const int Size = {schema.Size.ToString(CultureInfo.InvariantCulture)};");
        w.Line();
        EmitSchemaMembers(w, schema, "Schema", apache: false, types);
        w.Line();
        w.Line("/// <summary>Creates a value from exactly <see cref=\"Size\"/> bytes. The array is not copied.</summary>");
        w.Open($"public {name}(byte[] value)");
        w.Line($"Value = global::AvroSharp.Serialization.AvroGeneratedCode.CheckFixedSize(value, Size, {CSharpNames.Literal(schema.FullName)});");
        w.Close();
        w.Line();
        w.Line("/// <summary>Gets the bytes.</summary>");
        w.Line("public byte[] Value { get; }");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line($"public bool Equals({types.Nullable(name)} other) => !(other is null) && global::System.MemoryExtensions.SequenceEqual(new global::System.ReadOnlySpan<byte>(Value), other.Value);");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line($"public override bool Equals({types.Nullable("object")} obj) => obj is {name} other && Equals(other);");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Open("public override int GetHashCode()");
        w.Line("var hash = -2128831035;");
        w.Open("foreach (var b in Value)");
        w.Line("hash = (hash ^ b) * 16777619;");
        w.Close();
        w.Line();
        w.Line("return hash;");
        w.Close();
        w.Close();
    }

    /// <summary>
    /// The schema JSON and a lazily parsed <c>AvroSchema</c> property named <paramref name="propertyName"/>. With
    /// <paramref name="apache"/>, also the JSON that Apache.Avro can parse (see <see cref="ApacheSupport.SchemaJson"/>).
    /// </summary>
    private static void EmitSchemaMembers(CodeWriter w, NamedSchema schema, string propertyName, bool apache, TypeMapper types)
    {
        var json = schema.ToJson();
        w.Line("/// <summary>The Avro schema of this type, as JSON.</summary>");
        w.Line($"public const string SchemaJson = {CSharpNames.Literal(json)};");
        if (apache)
        {
            var apacheJson = ApacheSupport.SchemaJson(json);
            w.Line();
            w.Line("/// <summary>The schema as Apache.Avro parses it (it rejects uuid on fixed, which the specification allows).</summary>");
            w.Line($"internal const string ApacheSchemaJson = {(string.Equals(apacheJson, json, StringComparison.Ordinal) ? "SchemaJson" : CSharpNames.Literal(apacheJson))};");
        }

        w.Line();
        w.Line($"private static {types.Nullable("global::AvroSharp.Schemas.AvroSchema")} s_schema;");
        w.Line();
        w.Line("/// <summary>Gets the Avro schema of this type.</summary>");
        w.Line($"public static global::AvroSharp.Schemas.AvroSchema {propertyName} => s_schema ?? (s_schema = global::AvroSharp.Schemas.AvroSchema.Parse(SchemaJson));");
    }

    /// <summary>
    /// PascalCase property names, made unique: a name may not repeat the type's name (CS0542), a generated member, or
    /// another field's name after case conversion.
    /// </summary>
    private static string[] PropertyNames(RecordSchema record, string typeName, PropertyNaming naming)
    {
        var used = new HashSet<string>(StringComparer.Ordinal)
        {
            typeName.TrimStart('@'), "SchemaJson", "Schema", "Write", "Read", "WriteCore", "ReadCore", "ToAvroBytes",
            "FromAvroBytes", "ReadResolved", "Get", "Put", "Equals", "GetHashCode", "ToString", "GetType", "MemberwiseClone", "Finalize",
        };
        for (var i = 0; i < record.Fields.Count; i++)
        {
            used.Add("ReadResolvedField" + i.ToString(CultureInfo.InvariantCulture));
        }

        var result = new string[record.Fields.Count];
        for (var i = 0; i < result.Length; i++)
        {
            var candidate = naming == PropertyNaming.Avro ? record.Fields[i].Name : CSharpNames.Pascal(record.Fields[i].Name);
            while (!used.Add(candidate))
            {
                candidate += "_";
            }

            // Avro names are valid C# identifiers except for keywords, which are escaped.
            result[i] = CSharpNames.Identifier(candidate);
        }

        return result;
    }

    private static void Doc(CodeWriter w, string? doc)
    {
        if (string.IsNullOrWhiteSpace(doc))
        {
            return;
        }

        w.Line("/// <summary>");
        foreach (var line in doc!.Replace("\r\n", "\n").Split('\n'))
        {
            w.Line("/// " + CSharpNames.Xml(line.Trim()));
        }

        w.Line("/// </summary>");
    }
}
