using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using AvroSharp.Schemas;

namespace AvroSharp.CodeGen;

/// <summary>
/// Generates C# types for the named types (records, enums and fixed types) of Avro schemas. Each record gets static
/// <c>Write</c>/<c>Read</c> methods that call <c>AvroWriter</c>/<c>AvroReader</c> directly, in schema order.
/// </summary>
/// <remarks>Output is deterministic: the same schemas and options always produce the same files, in the same order.</remarks>
public static class CSharpCodeGenerator
{
    private const string Tool = "AvroSharp.CodeGen";

    /// <summary>Generates one source file per named type reachable from <paramref name="schemas"/>.</summary>
    /// <param name="schemas">The schemas. A named type reachable from several of them is generated once.</param>
    /// <param name="options">Options, or <see langword="null"/> for <see cref="CodeGenOptions.Default"/>.</param>
    public static IReadOnlyList<GeneratedSource> Generate(IEnumerable<AvroSchema> schemas, CodeGenOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(schemas);
        options ??= CodeGenOptions.Default;
        var names = new CSharpNames(options);
        var types = new TypeMapper(names);

        var named = new SortedDictionary<string, NamedSchema>(StringComparer.Ordinal);
        foreach (var schema in schemas)
        {
            Collect(schema, named);
        }

        var version = typeof(CSharpCodeGenerator).Assembly.GetName().Version?.ToString() ?? "0.0.0.0";
        return [.. named.Values.Select(schema => new GeneratedSource(schema.FullName + ".g.cs", Emit(schema, names, types, version)))];
    }

    private static void Collect(AvroSchema schema, SortedDictionary<string, NamedSchema> named)
    {
        switch (schema)
        {
            case NamedSchema namedSchema when named.ContainsKey(namedSchema.FullName):
                return;
            case RecordSchema record:
                named.Add(record.FullName, record);
                foreach (var field in record.Fields)
                {
                    Collect(field.Schema, named);
                }

                break;
            case NamedSchema namedSchema:
                named.Add(namedSchema.FullName, namedSchema);
                break;
            case ArraySchema array:
                Collect(array.Items, named);
                break;
            case MapSchema map:
                Collect(map.Values, named);
                break;
            case UnionSchema union:
                foreach (var branch in union.Branches)
                {
                    Collect(branch, named);
                }

                break;
        }
    }

    private static string Emit(NamedSchema schema, CSharpNames names, TypeMapper types, string version)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line($"// Generated by {Tool} from the Avro schema of '{schema.FullName}'. Do not edit.");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591 // Members without an Avro doc have no documentation comment.");
        w.Line();

        var ns = names.Namespace(schema);
        if (ns is not null)
        {
            w.Open($"namespace {ns}");
        }

        Doc(w, schema.Doc);
        w.Line($"[global::System.CodeDom.Compiler.GeneratedCode({CSharpNames.Literal(Tool)}, {CSharpNames.Literal(version)})]");
        var name = CSharpNames.Identifier(schema.Name.Name);
        switch (schema)
        {
            case RecordSchema record:
                EmitRecord(w, record, name, names, types);
                break;
            case EnumSchema enumSchema:
                EmitEnum(w, enumSchema, name);
                break;
            case FixedSchema fixedSchema:
                EmitFixed(w, fixedSchema, name);
                break;
        }

        if (ns is not null)
        {
            w.Close();
        }

        return w.ToString();
    }

    private const string Writer = "global::AvroSharp.IO.AvroWriter";
    private const string Reader = "global::AvroSharp.IO.AvroReader";
    private const string Support = "global::AvroSharp.Serialization.AvroGeneratedCode";

    private static void EmitRecord(CodeWriter w, RecordSchema record, string name, CSharpNames names, TypeMapper types)
    {
        var properties = PropertyNames(record, name);
        w.Open($"public sealed partial class {name}");
        EmitSchemaMembers(w, record);

        for (var i = 0; i < record.Fields.Count; i++)
        {
            var field = record.Fields[i];
            w.Line();
            Doc(w, field.Doc);
            var initializer = TypeMapper.Initializer(field.Schema);
            w.Line($"public {types.TypeOf(field.Schema)} {properties[i]} {{ get; set; }}{(initializer is null ? string.Empty : " = " + initializer + ";")}");
        }

        EmitRecordApi(w, name);
        EmitRecordCore(w, record, name, properties, new SerializerEmitter(names, types));
        w.Close();
    }

    /// <summary>The public entry points; they delegate to the depth-tracking cores.</summary>
    private static void EmitRecordApi(CodeWriter w, string name)
    {
        w.Line();
        w.Line("/// <summary>Writes a value in Avro binary encoding.</summary>");
        w.Open($"public static void Write(ref {Writer} writer, {name} value)");
        w.Open("if (value is null)");
        w.Line("throw new global::System.ArgumentNullException(nameof(value));");
        w.Close();
        w.Line();
        w.Line("WriteCore(ref writer, value, 0);");
        w.Close();

        w.Line();
        w.Line("/// <summary>Reads a value written with this type's schema.</summary>");
        w.Line($"public static {name} Read(ref {Reader} reader) => ReadCore(ref reader, 0);");

        w.Line();
        w.Line("/// <summary>Writes this value to a new array, in Avro binary encoding.</summary>");
        w.Line($"public byte[] ToAvroBytes() => {Support}.SerializeToArray(this, Write);");

        w.Line();
        w.Line("/// <summary>Reads a value from Avro binary data written with this type's schema.</summary>");
        w.Open($"public static {name} FromAvroBytes(global::System.ReadOnlySpan<byte> data)");
        w.Line($"var reader = new {Reader}(data);");
        w.Line("return ReadCore(ref reader, 0);");
        w.Close();
    }

    /// <summary>The serializers: each field in schema order, with the record depth checked on entry.</summary>
    private static void EmitRecordCore(CodeWriter w, RecordSchema record, string name, string[] properties, SerializerEmitter emitter)
    {
        w.Line();
        w.Open($"internal static void WriteCore(ref {Writer} writer, {name} value, int depth)");
        w.Open($"if (depth > {Support}.MaxDepth)");
        w.Line($"throw {Support}.WriteTooDeep();");
        w.Close();
        for (var i = 0; i < record.Fields.Count; i++)
        {
            w.Line();
            emitter.Write(w, record.Fields[i].Schema, "value." + properties[i], record.FullName + "." + record.Fields[i].Name);
        }

        w.Close();

        w.Line();
        w.Open($"internal static {name} ReadCore(ref {Reader} reader, int depth)");
        w.Open($"if (depth > {Support}.MaxDepth)");
        w.Line($"throw {Support}.ReadTooDeep();");
        w.Close();
        w.Line();
        w.Line($"var value = new {name}();");
        for (var i = 0; i < record.Fields.Count; i++)
        {
            emitter.Read(w, record.Fields[i].Schema, "value." + properties[i]);
        }

        w.Line("return value;");
        w.Close();
    }

    private static void EmitEnum(CodeWriter w, EnumSchema schema, string name)
    {
        w.Open($"public enum {name}");
        for (var i = 0; i < schema.Symbols.Count; i++)
        {
            w.Line($"{CSharpNames.Identifier(schema.Symbols[i])} = {i.ToString(CultureInfo.InvariantCulture)},");
        }

        w.Close();
    }

    private static void EmitFixed(CodeWriter w, FixedSchema schema, string name)
    {
        w.Open($"public sealed partial class {name} : global::System.IEquatable<{name}>");
        w.Line("/// <summary>The number of bytes in a value.</summary>");
        w.Line($"public const int Size = {schema.Size.ToString(CultureInfo.InvariantCulture)};");
        w.Line();
        EmitSchemaMembers(w, schema);
        w.Line();
        w.Line("/// <summary>Creates a value from exactly <see cref=\"Size\"/> bytes. The array is not copied.</summary>");
        w.Open($"public {name}(byte[] value)");
        w.Line($"Value = global::AvroSharp.Serialization.AvroGeneratedCode.CheckFixedSize(value, Size, {CSharpNames.Literal(schema.FullName)});");
        w.Close();
        w.Line();
        w.Line("/// <summary>Gets the bytes.</summary>");
        w.Line("public byte[] Value { get; }");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line($"public bool Equals({name}? other) => other is not null && global::System.MemoryExtensions.SequenceEqual(new global::System.ReadOnlySpan<byte>(Value), other.Value);");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line($"public override bool Equals(object? obj) => obj is {name} other && Equals(other);");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Open("public override int GetHashCode()");
        w.Line("var hash = -2128831035;");
        w.Open("foreach (var b in Value)");
        w.Line("hash = (hash ^ b) * 16777619;");
        w.Close();
        w.Line();
        w.Line("return hash;");
        w.Close();
        w.Close();
    }

    private static void EmitSchemaMembers(CodeWriter w, NamedSchema schema)
    {
        w.Line("/// <summary>The Avro schema of this type, as JSON.</summary>");
        w.Line($"public const string SchemaJson = {CSharpNames.Literal(schema.ToJson())};");
        w.Line();
        w.Line("private static global::AvroSharp.Schemas.AvroSchema? s_schema;");
        w.Line();
        w.Line("/// <summary>Gets the Avro schema of this type.</summary>");
        w.Line("public static global::AvroSharp.Schemas.AvroSchema Schema => s_schema ??= global::AvroSharp.Schemas.AvroSchema.Parse(SchemaJson);");
    }

    /// <summary>
    /// PascalCase property names, made unique: a name may not repeat the type's name (CS0542), a generated member, or
    /// another field's name after case conversion.
    /// </summary>
    private static string[] PropertyNames(RecordSchema record, string typeName)
    {
        var used = new HashSet<string>(StringComparer.Ordinal)
        {
            typeName.TrimStart('@'), "SchemaJson", "Schema", "Write", "Read", "WriteCore", "ReadCore", "ToAvroBytes",
            "FromAvroBytes", "Equals", "GetHashCode", "ToString", "GetType", "MemberwiseClone", "Finalize",
        };
        var result = new string[record.Fields.Count];
        for (var i = 0; i < result.Length; i++)
        {
            var candidate = CSharpNames.Pascal(record.Fields[i].Name);
            while (!used.Add(candidate))
            {
                candidate += "_";
            }

            result[i] = candidate;
        }

        return result;
    }

    private static void Doc(CodeWriter w, string? doc)
    {
        if (string.IsNullOrWhiteSpace(doc))
        {
            return;
        }

        w.Line("/// <summary>");
        foreach (var line in doc!.Replace("\r\n", "\n").Split('\n'))
        {
            w.Line("/// " + CSharpNames.Xml(line.Trim()));
        }

        w.Line("/// </summary>");
    }
}
