using System;
using System.Buffers;
using System.Collections.Concurrent;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using AvroSharp.Generic;
using AvroSharp.IO;
using AvroSharp.Schemas;
using AvroSharp.Serialization;
using Confluent.Kafka;
using Confluent.SchemaRegistry;
using ConfluentSchema = Confluent.SchemaRegistry.Schema;

namespace AvroSharp.Confluent;

/// <summary>
/// Reads values in Confluent Schema Registry framing as a type generated by AvroSharp, a primitive, or generic values
/// (<see cref="AvroSharpGeneric"/>). The writer's schema comes from the registry by the message's schema ID (Confluent's
/// client caches it), and the data is resolved to the type's own schema, so data of older and newer versions reads.
/// It derives from Confluent's <see cref="AsyncDeserializer{T, TParsedSchema}"/>.
/// </summary>
/// <typeparam name="T">The type read.</typeparam>
/// <remarks>
/// It is both asynchronous and synchronous (<see cref="IDeserializer{T}"/>), which Confluent.Kafka's consumer calls.
/// Once a schema ID's reader is known, the synchronous path reads without a task. It waits for the registry the first
/// time, and on every message with <c>use.latest.version</c> or <c>use.latest.with.metadata</c>, or whose schema has
/// rules, which can run asynchronously.
/// </remarks>
public sealed class AvroSharpDeserializer<T> : AsyncDeserializer<T, AvroSchema>, IDeserializer<T>
{
    private readonly AvroTypeInfo<T> _type;

    // The writer schema and reader of each schema ID, once known, when reading it depends on nothing else (no latest
    // schema, and no rules): the synchronous path reads with them.
    private readonly ConcurrentDictionary<(int? Id, Guid? Guid), (AvroSchema Writer, AvroReadFunc<T> Read)> _known = new();

    // The reader of each writer schema. Confluent's client caches a parsed schema per ID, so the instance is the key.
    private readonly ConditionalWeakTable<AvroSchema, AvroReadFunc<T>> _readers = new();
    private readonly ConditionalWeakTable<AvroSchema, AvroReadFunc<T>>.CreateValueCallback _createReader;

    // For generic values without a reader schema: the reader of each writer schema resolved to each latest schema.
    private readonly ConditionalWeakTable<AvroSchema, ConditionalWeakTable<AvroSchema, AvroReadFunc<T>>> _latestReaders = new();

    /// <summary>
    /// Creates a deserializer of a generated type or a primitive, which <see cref="AvroTypes"/> knows. On .NET Standard,
    /// pass the type's <c>AvroTypeInfo</c> to the other constructor, or register it first.
    /// </summary>
    /// <param name="client">The schema registry.</param>
    /// <param name="config">The settings, or <see langword="null"/> for the defaults.</param>
    /// <param name="ruleRegistry">The data contract rules, or <see langword="null"/> for <see cref="RuleRegistry.GlobalInstance"/>.</param>
    /// <exception cref="ArgumentException"><paramref name="config"/> has a key the deserializer doesn't know.</exception>
    /// <exception cref="InvalidOperationException"><typeparamref name="T"/> is not registered in <see cref="AvroTypes"/>.</exception>
    public AvroSharpDeserializer(ISchemaRegistryClient client, AvroSharpDeserializerConfig? config = null, RuleRegistry? ruleRegistry = null)
        : this(client, AvroTypes.Get<T>(), config, ruleRegistry)
    {
    }

    /// <summary>Creates a deserializer of the type that <paramref name="type"/> reads and writes.</summary>
    /// <param name="client">The schema registry.</param>
    /// <param name="type">The type's schema and serializers.</param>
    /// <param name="config">The settings, or <see langword="null"/> for the defaults.</param>
    /// <param name="ruleRegistry">The data contract rules, or <see langword="null"/> for <see cref="RuleRegistry.GlobalInstance"/>.</param>
    /// <exception cref="ArgumentException"><paramref name="config"/> has a key the deserializer doesn't know.</exception>
    public AvroSharpDeserializer(ISchemaRegistryClient client, AvroTypeInfo<T> type, AvroSharpDeserializerConfig? config = null, RuleRegistry? ruleRegistry = null)
        : base(client, config, ruleRegistry ?? RuleRegistry.GlobalInstance)
    {
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(type);
        _type = type;
        _createReader = schema => _type.ReadFor(schema);
        subjectNameStrategy = (config?.SubjectNameStrategy ?? SubjectNameStrategy.Associated).ToAsyncDelegate(client, config);
        if (config is null)
        {
            return;
        }

        ConfigKeys.Check(config, ConfigKeys.Deserializer, "AvroSharpDeserializer");
        useLatestVersion = config.UseLatestVersion ?? useLatestVersion;
        useLatestWithMetadata = config.UseLatestWithMetadata ?? useLatestWithMetadata;
        if (config.SchemaIdStrategy is { } strategy)
        {
            schemaIdDecoder = strategy.ToDeserializer();
        }
    }

    /// <summary>Reads a value: the writer's schema by the message's schema ID, then the data resolved to the type's schema.</summary>
    /// <param name="data">The message body.</param>
    /// <param name="isNull">Whether the message has no body; the result is then the default of <typeparamref name="T"/>.</param>
    /// <param name="context">The topic, the component (key or value) and the headers.</param>
    public override async Task<T> DeserializeAsync(ReadOnlyMemory<byte> data, bool isNull, SerializationContext context)
    {
        if (isNull)
        {
            return Tombstone();
        }

        var isKey = context.Component == MessageComponentType.Key;
        var subject = await GetSubjectName(context.Topic, isKey, null).ConfigureAwait(false);
        var id = new SchemaId(SchemaType.Avro);
        var payload = schemaIdDecoder.Decode(data, context, ref id);
        var (writerJson, writerSchema) = await GetWriterSchema(subject, id).ConfigureAwait(false);
        subject ??= await GetSubjectName(context.Topic, isKey, (writerSchema as RecordSchema)?.FullName).ConfigureAwait(false);
        var latest = subject is null ? null : await GetReaderSchema(subject).ConfigureAwait(false);

        if (writerJson.RuleSet?.EncodingRules is { Count: > 0 })
        {
            var decoded = await ExecuteRules(isKey, subject, context.Topic, context.Headers, RulePhase.Encoding, RuleMode.Read, null, writerJson, payload, null).ConfigureAwait(false);
            payload = decoded is byte[] bytes ? bytes : (ReadOnlyMemory<byte>)decoded!;
        }

        if (latest is not null && (await GetMigrations(subject!, writerJson, latest).ConfigureAwait(false)).Count > 0)
        {
            throw new NotSupportedException($"The subject '{subject}' has migration rules between the writer's schema and the latest, which AvroSharp.Confluent doesn't run yet.");
        }

        var read = ReadAsLatest is not null && latest is not null
            ? LatestReader(writerSchema, await GetParsedSchema(latest).ConfigureAwait(false))
            : _readers.GetValue(writerSchema, _createReader);
        var value = Read(read, writerSchema, payload);
        var target = (ConfluentSchema?)latest ?? writerJson;
        if (target.RuleSet?.DomainRules is { Count: > 0 })
        {
            if (ApacheAvroGeneric.HasCelRules(target.RuleSet) && !RegistrySchemas.IsRawBytes(writerSchema) && ApacheAvroGeneric.IsAvailable)
            {
                // CEL reads a value by its Avro field names only as Apache.Avro's generic model: the rules see the data
                // decoded that way, in the rules' schema. A rule that returns another value (a transform) is read back.
                var targetSchema = latest is null ? writerSchema : await GetParsedSchema(latest).ConfigureAwait(false);
                var generic = ApacheAvroGeneric.Decode(writerSchema, targetSchema, payload);
                var result = await ExecuteRules(isKey, subject, context.Topic, context.Headers, RuleMode.Read, null, target, generic, RuleSupport.NoFieldTransformsAsync).ConfigureAwait(false);
                if (!ReferenceEquals(result, generic) || ApacheAvroGeneric.HasTransforms(target.RuleSet))
                {
                    value = Read(_readers.GetValue(targetSchema, _createReader), targetSchema, ApacheAvroGeneric.Encode(targetSchema, result));
                }
            }
            else
            {
                value = (T)(await ExecuteRules(isKey, subject, context.Topic, context.Headers, RuleMode.Read, null, target, value, RuleSupport.NoFieldTransformsAsync).ConfigureAwait(false))!;
            }
        }
        else if (latest is null && !useLatestVersion && useLatestWithMetadata is null && writerJson.RuleSet?.EncodingRules is not { Count: > 0 })
        {
            _known.TryAdd((id.Id, id.Guid), (writerSchema, read));
        }

        return value;
    }

    /// <summary>
    /// Reads a value without a task once its schema ID's reader is known; until then, and with settings or rules that
    /// can run asynchronously, it waits for <see cref="DeserializeAsync"/>.
    /// </summary>
    /// <param name="data">The message body.</param>
    /// <param name="isNull">Whether the message has no body; the result is then the default of <typeparamref name="T"/>.</param>
    /// <param name="context">The topic, the component (key or value) and the headers.</param>
    [SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "Confluent.Kafka's consumer calls deserializers synchronously: it waits only until the schema ID's reader is known, or with settings or rules that can run asynchronously.")]
    public T Deserialize(ReadOnlySpan<byte> data, bool isNull, SerializationContext context)
    {
        if (isNull)
        {
            return Tombstone();
        }

        var message = data.ToArray();
        var id = new SchemaId(SchemaType.Avro);
        var payload = schemaIdDecoder.Decode(message, context, ref id);
        return _known.TryGetValue((id.Id, id.Guid), out var known)
            ? Read(known.Read, known.Writer, payload)
            : DeserializeAsync(message, isNull: false, context).GetAwaiter().GetResult();
    }

    /// <inheritdoc/>
    protected override Task<AvroSchema> ParseSchema(ConfluentSchema schema) => RegistrySchemas.ParseAsync(schema, ResolveReferences);

    // A tombstone. A value type can't be null (a generic value can: AvroValue's default is null), as in Confluent's
    // deserializer.
    private static T Tombstone() =>
        default(T) is null || typeof(T) == typeof(AvroValue)
            ? default!
            : throw new InvalidOperationException($"The message has no body (a tombstone), which can't be read as the value type {typeof(T).Name}.");

    /// <summary>
    /// Gets or sets how values are read when the subject has a latest schema (<c>use.latest.version</c> or
    /// <c>use.latest.with.metadata</c>): resolved from the writer's schema to it, as Confluent's generic deserializer
    /// reads. <see langword="null"/> reads them as the type's schema, as for generated types.
    /// </summary>
    internal Func<AvroSchema, AvroSchema, AvroReadFunc<T>>? ReadAsLatest { get; init; }

    private AvroReadFunc<T> LatestReader(AvroSchema writerSchema, AvroSchema latestSchema) =>
        _latestReaders.GetOrCreateValue(writerSchema).GetValue(latestSchema, latest => ReadAsLatest!(writerSchema, latest));

    private static T Read(AvroReadFunc<T> read, AvroSchema writerSchema, ReadOnlyMemory<byte> payload)
    {
        if (RegistrySchemas.IsRawBytes(writerSchema))
        {
            // A value of the schema "bytes" is the message body alone, without Avro's length prefix, as Confluent's
            // serdes (.NET and Java) write it.
            var encoded = new ArrayBufferWriter<byte>(payload.Length + 10);
            var writer = new AvroWriter(encoded);
            writer.WriteBytes(payload.Span);
            writer.Flush();
            var bytesReader = new AvroReader(encoded.WrittenSpan);
            return read(ref bytesReader);
        }

        var reader = new AvroReader(payload.Span);
        return read(ref reader);
    }
}
