using System;
using System.Buffers;
using System.Collections.Concurrent;
using System.Diagnostics.CodeAnalysis;
using System.Threading.Tasks;
using AvroSharp.Generic;
using AvroSharp.IO;
using AvroSharp.Schemas;
using AvroSharp.Serialization;
using Confluent.Kafka;
using Confluent.SchemaRegistry;
using ConfluentSchema = Confluent.SchemaRegistry.Schema;

namespace AvroSharp.Confluent;

/// <summary>
/// Writes values in Confluent Schema Registry framing: a type generated by AvroSharp (from <c>.avsc</c> files or
/// <c>[AvroSerializable]</c>), a primitive, or generic values (<see cref="AvroSharpGeneric"/>). It derives from
/// Confluent's <see cref="AsyncSerializer{T, TParsedSchema}"/>, so subject name strategies, registration,
/// <c>use.latest.version</c>, schema ID strategies, references and rules are Confluent's own code; only the Avro
/// encoding is AvroSharp's. The bytes are those of Confluent's Avro serializer for the same schema and value.
/// </summary>
/// <typeparam name="T">The type written.</typeparam>
/// <remarks>
/// It is both asynchronous and synchronous (<see cref="ISerializer{T}"/>), so <c>producer.Produce</c> works too.
/// Confluent.Kafka's producer builder has a <c>SetValueSerializer</c> for each, so pass it as one of them, such as
/// <c>(ISerializer&lt;T&gt;)serializer</c>, or use <see cref="AvroSharpSerdeExtensions"/>, which set the synchronous one.
/// Once a topic's schema ID is known, the synchronous path writes without a task. It waits for the registry the first
/// time, and on every message with <c>use.latest.version</c>, <c>use.latest.with.metadata</c> or <c>use.schema.id</c>,
/// whose rules can run asynchronously.
/// </remarks>
public sealed class AvroSharpSerializer<T> : AsyncSerializer<T, AvroSchema>, ISerializer<T>
{
    private readonly AvroTypeInfo<T> _type;
    private readonly string _schemaJson;
    private readonly string? _recordName;
    private readonly bool _rawBytes;
    private readonly ConcurrentDictionary<int, bool> _writesAs = new();
    private readonly ConcurrentDictionary<string, SchemaId> _registered = new(StringComparer.Ordinal);

    // The schema ID of each topic, for keys and for values, once known, when the ID depends on nothing else (without
    // use.latest.version, use.latest.with.metadata and use.schema.id): the synchronous path writes with it.
    private readonly ConcurrentDictionary<(string Topic, bool IsKey), SchemaId> _topicIds = new();

    /// <summary>
    /// Creates a serializer of a generated type or a primitive, which <see cref="AvroTypes"/> knows. Generated types
    /// register themselves on .NET 5 and later; on .NET Standard, pass the type's <c>AvroTypeInfo</c> to the other
    /// constructor, or register it first.
    /// </summary>
    /// <param name="client">The schema registry.</param>
    /// <param name="config">The settings, or <see langword="null"/> for the defaults.</param>
    /// <param name="ruleRegistry">The data contract rules, or <see langword="null"/> for <see cref="RuleRegistry.GlobalInstance"/>.</param>
    /// <exception cref="InvalidOperationException"><typeparamref name="T"/> is not registered in <see cref="AvroTypes"/>.</exception>
    /// <exception cref="ArgumentException"><paramref name="config"/> has a key the serializer doesn't know, or enables both <c>use.latest.version</c> and <c>auto.register.schemas</c> (the default).</exception>
    public AvroSharpSerializer(ISchemaRegistryClient client, AvroSharpSerializerConfig? config = null, RuleRegistry? ruleRegistry = null)
        : this(client, AvroTypes.Get<T>(), config, ruleRegistry)
    {
    }

    /// <summary>Creates a serializer of the type that <paramref name="type"/> reads and writes.</summary>
    /// <param name="client">The schema registry.</param>
    /// <param name="type">The type's schema and serializers.</param>
    /// <param name="config">The settings, or <see langword="null"/> for the defaults.</param>
    /// <param name="ruleRegistry">The data contract rules, or <see langword="null"/> for <see cref="RuleRegistry.GlobalInstance"/>.</param>
    /// <exception cref="ArgumentException"><paramref name="config"/> has a key the serializer doesn't know, or enables both <c>use.latest.version</c> and <c>auto.register.schemas</c> (the default).</exception>
    public AvroSharpSerializer(ISchemaRegistryClient client, AvroTypeInfo<T> type, AvroSharpSerializerConfig? config = null, RuleRegistry? ruleRegistry = null)
        : base(client, config, ruleRegistry ?? RuleRegistry.GlobalInstance)
    {
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(type);
        _type = type;
        _schemaJson = type.Schema.ToJson();
        // The record name for the Record and TopicRecord strategies: only a record has one, as in Confluent's .NET and
        // Java serializers, so the subjects match theirs.
        _recordName = (type.Schema as RecordSchema)?.FullName;
        _rawBytes = RegistrySchemas.IsRawBytes(type.Schema);
        subjectNameStrategy = (config?.SubjectNameStrategy ?? SubjectNameStrategy.Associated).ToAsyncDelegate(client, config);
        if (config is null)
        {
            return;
        }

        ConfigKeys.Check(config, ConfigKeys.Serializer, "AvroSharpSerializer");
        autoRegisterSchema = config.AutoRegisterSchemas ?? autoRegisterSchema;
        normalizeSchemas = config.NormalizeSchemas ?? normalizeSchemas;
        useSchemaId = config.UseSchemaId ?? useSchemaId;
        useLatestVersion = config.UseLatestVersion ?? useLatestVersion;
        useLatestWithMetadata = config.UseLatestWithMetadata ?? useLatestWithMetadata;
        initialBufferSize = config.BufferBytes ?? initialBufferSize;
        if (config.SchemaIdStrategy is { } strategy)
        {
            schemaIdEncoder = strategy.ToEncoder();
        }

        if (useLatestVersion && autoRegisterSchema)
        {
            throw new ArgumentException("use.latest.version and auto.register.schemas can't both be enabled: set AutoRegisterSchemas to false.", nameof(config));
        }
    }

    /// <summary>Writes a value: its schema ID (registered or looked up once per subject), then its Avro encoding.</summary>
    /// <param name="value">The value. A <see langword="null"/> reference is written as no message body.</param>
    /// <param name="context">The topic, the component (key or value) and the headers.</param>
    /// <returns>The message body, or <see langword="null"/> for a tombstone.</returns>
    public override async Task<byte[]?> SerializeAsync(T value, SerializationContext context)
    {
        if (IsTombstone(value))
        {
            return null;
        }

        var isKey = context.Component == MessageComponentType.Key;
        var subject = await GetSubjectName(context.Topic, isKey, _recordName).ConfigureAwait(false);
        if (subject is null)
        {
            // Confluent's base class needs a subject for use.schema.id too: its client looks the ID up within the
            // subject, and throws ArgumentNullException without one, as Confluent's own serializer does.
            throw new InvalidOperationException(
                $"The subject name strategy gave no subject for the topic '{context.Topic}'. The Record and TopicRecord " +
                "strategies need a schema with a name; the None strategy isn't supported, with or without use.schema.id.");
        }

        var latest = await GetReaderSchema(subject).ConfigureAwait(false);
        if (latest is null)
        {
            var registered = await IdForAsync(subject!).ConfigureAwait(false);
            if (useSchemaId < 0 && !useLatestVersion && useLatestWithMetadata is null)
            {
                _topicIds.TryAdd((context.Topic, isKey), registered);
            }

            return Encode(value, ref context, registered);
        }

        await CheckWritesAsAsync(latest).ConfigureAwait(false);
        var id = new SchemaId(SchemaType.Avro, latest.Id, latest.Guid);
        var header = schemaIdEncoder.CalculateSize(ref id);

        // The message body, when the domain rules ran on the encoded value rather than on the value.
        byte[]? body = null;
        if (latest.RuleSet?.DomainRules is { Count: > 0 })
        {
            (value, body) = await DomainRulesAsync(value, isKey, subject, context, latest, header).ConfigureAwait(false);
        }

        if (latest.RuleSet?.EncodingRules is not { Count: > 0 })
        {
            return body is null ? Encode(value, ref context, id) : Frame(header, body, ref context, ref id);
        }

        // Encoding rules (such as payload encryption) take and return the encoded bytes.
        body ??= Body(Write(value, header).WrittenSpan[header..]).ToArray();
        var encoded = (byte[])(await ExecuteRules(isKey, subject, context.Topic, context.Headers, RulePhase.Encoding, RuleMode.Write, null, latest, body, null).ConfigureAwait(false))!;
        return Frame(header, encoded, ref context, ref id);
    }

    // Runs the domain rules on a value. Field rules, such as field-level encryption, aren't supported yet.
    private async Task<(T Value, byte[]? Body)> DomainRulesAsync(T value, bool isKey, string subject, SerializationContext context, RegisteredSchema latest, int header)
    {
        if (!ApacheAvroGeneric.HasCelRules(latest.RuleSet) || _rawBytes || !ApacheAvroGeneric.IsAvailable)
        {
            return ((T)(await ExecuteRules(isKey, subject, context.Topic, context.Headers, RuleMode.Write, null, latest, value, RuleSupport.NoFieldTransformsAsync).ConfigureAwait(false))!, null);
        }

        // CEL reads a value by its Avro field names only as Apache.Avro's generic model, which Java's and Confluent's
        // serializers give it: so the rules see the value decoded that way. A rule that returns another value (a
        // transform) changes what is written.
        var body = Body(Write(value, header).WrittenSpan[header..]).ToArray();
        var schema = await GetParsedSchema(latest).ConfigureAwait(false);
        var generic = ApacheAvroGeneric.Decode(schema, schema, body);
        var result = await ExecuteRules(isKey, subject, context.Topic, context.Headers, RuleMode.Write, null, latest, generic, RuleSupport.NoFieldTransformsAsync).ConfigureAwait(false);
        return (value, ReferenceEquals(result, generic) && !ApacheAvroGeneric.HasTransforms(latest.RuleSet) ? body : ApacheAvroGeneric.Encode(schema, result).ToArray());
    }

    /// <summary>
    /// Writes a value without a task once the topic's schema ID is known; until then, and with settings whose rules can
    /// run asynchronously, it waits for <see cref="SerializeAsync"/>.
    /// </summary>
    /// <param name="data">The value. A <see langword="null"/> reference is written as no message body.</param>
    /// <param name="context">The topic, the component (key or value) and the headers.</param>
    /// <returns>The message body, or <see langword="null"/> for a tombstone.</returns>
    [SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "Confluent.Kafka's synchronous interface: it waits only until the topic's schema ID is known, or with settings whose rules can run asynchronously.")]
    public byte[]? Serialize(T data, SerializationContext context)
    {
        if (IsTombstone(data))
        {
            return null;
        }

        return _topicIds.TryGetValue((context.Topic, context.Component == MessageComponentType.Key), out var id)
            ? Encode(data, ref context, id)
            : SerializeAsync(data, context).GetAwaiter().GetResult();
    }

    /// <inheritdoc/>
    protected override Task<AvroSchema> ParseSchema(ConfluentSchema schema) => RegistrySchemas.ParseAsync(schema, ResolveReferences);

    // A null value is a tombstone: no message body. So is a null generic value, unless the schema is "null".
    private bool IsTombstone(T value) =>
        value is null || (value is AvroValue { IsNull: true } && _type.Schema.Type != AvroSchemaType.Null);

    // The message: the schema ID, then the value's encoding (or the bytes alone, for the schema "bytes").
    private byte[] Encode(T value, ref SerializationContext context, SchemaId id)
    {
        var header = schemaIdEncoder.CalculateSize(ref id);
        var output = Write(value, header);
        if (_rawBytes)
        {
            return Frame(header, Body(output.WrittenSpan[header..]), ref context, ref id);
        }

        var result = output.WrittenSpan.ToArray();
        schemaIdEncoder.Encode(result, ref context, ref id);
        return result;
    }

    // The value's encoding, after room for the header.
    private ArrayBufferWriter<byte> Write(T value, int header)
    {
        var output = new ArrayBufferWriter<byte>(Math.Max(initialBufferSize, header + 16));
        output.Advance(header);
        var writer = new AvroWriter(output);
        _type.Write(ref writer, value);
        writer.Flush();
        return output;
    }

    // The message body of an encoded value. A value of the schema "bytes" is the bytes alone, without Avro's length
    // prefix, as Confluent's serdes (.NET and Java) write it.
    private ReadOnlySpan<byte> Body(ReadOnlySpan<byte> encoded)
    {
        if (!_rawBytes)
        {
            return encoded;
        }

        var reader = new AvroReader(encoded);
        reader.ReadLong();
        return encoded[(int)reader.BytesConsumed..];
    }

    private byte[] Frame(int header, ReadOnlySpan<byte> body, ref SerializationContext context, ref SchemaId id)
    {
        var framed = new byte[header + body.Length];
        schemaIdEncoder.Encode(framed, ref context, ref id);
        body.CopyTo(framed.AsSpan(header));
        return framed;
    }

    // With use.latest.version, use.latest.with.metadata or use.schema.id, the message carries another schema's ID,
    // but its bytes are still written in the type's schema. Readers decode them with that other schema, so the two
    // must encode alike: the same Parsing Canonical Form, and the same logical types (SchemaEncoding). Checked once per
    // schema ID.
    private async Task CheckWritesAsAsync(RegisteredSchema target)
    {
        if (_writesAs.ContainsKey(target.Id))
        {
            return;
        }

        var parsed = await GetParsedSchema(target).ConfigureAwait(false);
        if (!SchemaEncoding.Same(parsed, _type.Schema))
        {
            throw new InvalidOperationException(
                $"The message would carry the schema ID {target.Id} (version {target.Version} of '{target.Subject}'), but " +
                $"{typeof(T).Name} is written with a schema that encodes differently (another structure, or other logical " +
                "types), which readers would decode wrongly. Use a type generated from that schema, or turn off " +
                "use.latest.version, use.latest.with.metadata and use.schema.id.");
        }

        _writesAs.TryAdd(target.Id, true);
    }

    // The schema's ID in the subject: registered (or looked up, without auto-registration) once, then cached. A cached
    // ID is read without the lock.
    private async Task<SchemaId> IdForAsync(string subject)
    {
        if (_registered.TryGetValue(subject, out var known))
        {
            return known;
        }

        await serdeMutex.WaitAsync().ConfigureAwait(false);
        try
        {
            if (_registered.TryGetValue(subject, out var cached))
            {
                return cached;
            }

            var schema = new ConfluentSchema(_schemaJson, [], SchemaType.Avro);
            var registered = autoRegisterSchema
                ? await schemaRegistryClient.RegisterSchemaWithResponseAsync(subject, schema, normalizeSchemas).ConfigureAwait(false)
                : await schemaRegistryClient.LookupSchemaAsync(subject, schema, ignoreDeletedSchemas: true, normalizeSchemas).ConfigureAwait(false);
            var id = new SchemaId(SchemaType.Avro, registered.Id, registered.Guid);
            _registered.TryAdd(subject, id);
            return id;
        }
        finally
        {
            serdeMutex.Release();
        }
    }
}
