<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AvroSharp</RootNamespace>
    <PackageId>AvroSharp</PackageId>
  </PropertyGroup>

  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.IO.Pipelines" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>

</Project>
