// <auto-generated/>
// Generated by AvroSharp.CodeGen from the Avro schema of 'app.events.Event'. Do not edit.
#nullable enable
#pragma warning disable CS1591, CS8981

namespace app.events
{
    /// <summary>
    /// Something that happened.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("AvroSharp.CodeGen", "<version>")]
    [global::System.Diagnostics.DebuggerDisplay("Id = {Id}, Kind = {Kind}")]
    public sealed partial class Event : global::AvroSharp.Serialization.IAvroSpecificRecord, global::AvroSharp.Serialization.IAvroWritable, global::AvroSharp.Serialization.IAvroReadable
#if NET8_0_OR_GREATER
        , global::AvroSharp.Serialization.IAvroSerializable<Event>
#endif
    {
        private static global::AvroSharp.Schemas.AvroSchema? s_schema;

#if NET8_0_OR_GREATER
        private static global::System.ReadOnlySpan<byte> SchemaUtf8 =>
            "{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"app.events\",\"doc\":\"Something that happened.\",\"fields\":["u8 +
            "{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"kind\",\"type\":{\"type\":\"enum\",\"name\":\"Kind\",\"symbols\":[\"CREATED\","u8 +
            "\"DELETED\"]}},{\"name\":\"hash\",\"type\":{\"type\":\"fixed\",\"name\":\"Hash\",\"size\":2}},{\"name\":\"tags\",\"type\":{\""u8 +
            "type\":\"array\",\"items\":\"string\"}},{\"name\":\"scores\",\"type\":{\"type\":\"map\",\"values\":\"double\"}},{\"name\":\""u8 +
            "parent\",\"type\":[\"null\",\"Event\"]},{\"name\":\"payload\",\"type\":[\"null\",\"int\",\"string\"]}]}"u8;

        private static string? s_schemaJson;

        /// <summary>Gets the Avro schema of this type, as JSON.</summary>
        public static string SchemaJson => s_schemaJson ??= global::System.Text.Encoding.UTF8.GetString(SchemaUtf8);

        /// <summary>Gets the Avro schema of this type.</summary>
        public static global::AvroSharp.Schemas.AvroSchema Schema => s_schema ?? global::AvroSharp.Serialization.AvroGeneratedCode.PublishSchema(ref s_schema, global::AvroSharp.Schemas.AvroSchema.Parse(SchemaUtf8));
#else
        /// <summary>Gets the Avro schema of this type, as JSON.</summary>
        public static string SchemaJson =>
            "{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"app.events\",\"doc\":\"Something that happened.\",\"fields\":[" +
            "{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"kind\",\"type\":{\"type\":\"enum\",\"name\":\"Kind\",\"symbols\":[\"CREATED\"," +
            "\"DELETED\"]}},{\"name\":\"hash\",\"type\":{\"type\":\"fixed\",\"name\":\"Hash\",\"size\":2}},{\"name\":\"tags\",\"type\":{\"" +
            "type\":\"array\",\"items\":\"string\"}},{\"name\":\"scores\",\"type\":{\"type\":\"map\",\"values\":\"double\"}},{\"name\":\"" +
            "parent\",\"type\":[\"null\",\"Event\"]},{\"name\":\"payload\",\"type\":[\"null\",\"int\",\"string\"]}]}";

        /// <summary>Gets the Avro schema of this type.</summary>
        public static global::AvroSharp.Schemas.AvroSchema Schema => s_schema ?? global::AvroSharp.Serialization.AvroGeneratedCode.PublishSchema(ref s_schema, global::AvroSharp.Schemas.AvroSchema.Parse(SchemaJson));
#endif

        public long Id { get; set; }

        public global::app.events.Kind Kind { get; set; }

        public global::app.events.Hash Hash { get; set; }

        public global::System.Collections.Generic.List<string> Tags { get; set; }

        public global::System.Collections.Generic.Dictionary<string, double> Scores { get; set; }

        public global::app.events.Event? Parent { get; set; }

        public object? Payload { get; set; }

        /// <summary>Creates a value in which every field with a default in the schema has it.</summary>
        public Event()
        {
            Hash = null!;
            Tags = new global::System.Collections.Generic.List<string>();
            Scores = new global::System.Collections.Generic.Dictionary<string, double>();
        }

#pragma warning disable CS8618 // Readers set every field.
        private Event(global::AvroSharp.Serialization.AvroUninitialized _)
        {
        }
#pragma warning restore CS8618

        /// <summary>Writes a value in Avro binary encoding.</summary>
        public static void Write(ref global::AvroSharp.IO.AvroWriter writer, Event value)
        {
            if (value is null)
            {
                throw new global::System.ArgumentNullException(nameof(value));
            }

            WriteCore(ref writer, value, 0);
        }

        /// <summary>Reads a value written with this type's schema.</summary>
        public static Event Read(ref global::AvroSharp.IO.AvroReader reader)
        {
            global::AvroSharp.Serialization.AvroGeneratedCode.BeginRead(ref reader);
            return ReadCore(ref reader, null, 0);
        }

        /// <summary>Writes this value to a new array, in Avro binary encoding.</summary>
        public byte[] ToAvroBytes() => global::AvroSharp.Serialization.AvroGeneratedCode.SerializeToArray(this, Write);

        /// <summary>Writes this value into <paramref name="destination"/>, allocating nothing.</summary>
        /// <returns><see langword="true"/> when it fit; otherwise <paramref name="bytesWritten"/> is 0.</returns>
        public bool TryWriteAvroBytes(global::System.Span<byte> destination, out int bytesWritten)
        {
            var writer = global::AvroSharp.Serialization.AvroGeneratedCode.BeginTryWrite(destination);
            WriteCore(ref writer, this, 0);
            return global::AvroSharp.Serialization.AvroGeneratedCode.EndTryWrite(ref writer, out bytesWritten);
        }

        /// <summary>Writes this value into <paramref name="destination"/> and returns the bytes written; throws when it does not fit.</summary>
        public int WriteAvroBytes(global::System.Span<byte> destination)
        {
            var writer = new global::AvroSharp.IO.AvroWriter(destination);
            WriteCore(ref writer, this, 0);
            return (int)writer.BytesWritten;
        }

        /// <summary>Writes this value to <paramref name="output"/>, allocating nothing for a reused buffer writer.</summary>
        public void WriteAvroBytes(global::System.Buffers.IBufferWriter<byte> output)
        {
            var writer = new global::AvroSharp.IO.AvroWriter(output);
            WriteCore(ref writer, this, 0);
            writer.Flush();
        }

        /// <summary>Writes this value (<c>IAvroWritable</c>).</summary>
        public void WriteTo(ref global::AvroSharp.IO.AvroWriter writer) => WriteCore(ref writer, this, 0);

        /// <summary>Reads a value into this instance, filling its lists, dictionaries and records again (<c>IAvroReadable</c>).</summary>
        public void ReadFrom(ref global::AvroSharp.IO.AvroReader reader)
        {
            global::AvroSharp.Serialization.AvroGeneratedCode.BeginRead(ref reader);
            ReadCore(ref reader, this, 0);
        }

        /// <summary>Reads a value from Avro binary data written with this type's schema.</summary>
        public static Event FromAvroBytes(global::System.ReadOnlySpan<byte> data)
        {
            var reader = new global::AvroSharp.IO.AvroReader(data);
            return ReadCore(ref reader, null, 0);
        }

        /// <summary>Reads a value from the start of <paramref name="data"/> and reports how many bytes it took.</summary>
        public static Event FromAvroBytes(global::System.ReadOnlySpan<byte> data, out int bytesConsumed)
        {
            var reader = new global::AvroSharp.IO.AvroReader(data);
            var value = ReadCore(ref reader, null, 0);
            bytesConsumed = (int)reader.BytesConsumed;
            return value;
        }

        /// <summary>Reads a value from a sequence of buffers, such as a <c>PipeReader</c> result.</summary>
        public static Event FromAvroBytes(in global::System.Buffers.ReadOnlySequence<byte> data)
        {
            var reader = new global::AvroSharp.IO.AvroReader(data);
            return ReadCore(ref reader, null, 0);
        }

        private static global::AvroSharp.Serialization.AvroPlanCache? s_plan;

        /// <summary>
        /// Reads a value written with <paramref name="writerSchema"/>, another version of this type's schema, resolving the
        /// differences as the specification allows (added fields take their defaults, removed fields are skipped, numbers
        /// are promoted). Data written with this type's own schema is read directly.
        /// </summary>
        public static Event Read(ref global::AvroSharp.IO.AvroReader reader, global::AvroSharp.Schemas.AvroSchema writerSchema)
        {
            global::AvroSharp.Serialization.AvroGeneratedCode.BeginRead(ref reader);
            if (global::AvroSharp.Serialization.AvroGeneratedCode.IsSameSchema(writerSchema, Schema))
            {
                return ReadCore(ref reader, null, 0);
            }

            var plan = global::AvroSharp.Serialization.AvroGeneratedCode.GetRecordPlan(writerSchema, Schema, ref s_plan);
            if (plan != null)
            {
                return ReadResolved(ref reader, plan, 0);
            }

            return FromAvroBytes(global::AvroSharp.Serialization.AvroGeneratedCode.ResolveToReaderEncoding(ref reader, writerSchema, Schema));
        }

        /// <summary>Reads a value from Avro binary data written with <paramref name="writerSchema"/>, resolving schema differences.</summary>
        public static Event FromAvroBytes(global::System.ReadOnlySpan<byte> data, global::AvroSharp.Schemas.AvroSchema writerSchema)
        {
            var reader = new global::AvroSharp.IO.AvroReader(data);
            return Read(ref reader, writerSchema);
        }

        global::AvroSharp.Schemas.RecordSchema global::AvroSharp.Serialization.IAvroSpecificRecord.Schema => (global::AvroSharp.Schemas.RecordSchema)Schema;

        /// <summary>Gets the value of the field at a position in the schema, boxed.</summary>
        public object? Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0:
                    return this.Id;
                case 1:
                    return this.Kind;
                case 2:
                    return this.Hash;
                case 3:
                    return this.Tags;
                case 4:
                    return this.Scores;
                case 5:
                    return this.Parent;
                case 6:
                    return this.Payload;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidFieldPosition(fieldPos, 7, "app.events.Event");
            }
        }

        /// <summary>Sets the value of the field at a position in the schema; the value must have the field's C# type.</summary>
        public void Put(int fieldPos, object? fieldValue)
        {
            switch (fieldPos)
            {
                case 0:
                    this.Id = fieldValue is long v0 ? v0 : throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, Schema, 0, "long");
                    break;
                case 1:
                    this.Kind = fieldValue is global::app.events.Kind v1 ? v1 : throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, Schema, 1, "app.events.Kind");
                    break;
                case 2:
                    this.Hash = fieldValue as global::app.events.Hash ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, Schema, 2, "app.events.Hash");
                    break;
                case 3:
                    this.Tags = fieldValue as global::System.Collections.Generic.List<string> ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, Schema, 3, "System.Collections.Generic.List<string>");
                    break;
                case 4:
                    this.Scores = fieldValue as global::System.Collections.Generic.Dictionary<string, double> ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, Schema, 4, "System.Collections.Generic.Dictionary<string, double>");
                    break;
                case 5:
                    this.Parent = fieldValue == null ? (global::app.events.Event?)null : fieldValue as global::app.events.Event ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, Schema, 5, "app.events.Event?");
                    break;
                case 6:
                    this.Payload = fieldValue;
                    break;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidFieldPosition(fieldPos, 7, "app.events.Event");
            }
        }

        /// <summary>Reads and writes this type for the collection and union helpers of <c>AvroGeneratedCode</c>.</summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        internal readonly struct AvroCodec : global::AvroSharp.Serialization.IAvroCodec<Event>
        {
            public Event Read(ref global::AvroSharp.IO.AvroReader reader, int depth) => ReadCore(ref reader, null, depth);

            public void Write(ref global::AvroSharp.IO.AvroWriter writer, Event value, int depth) => WriteCore(ref writer, value, depth);
        }

        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static void WriteCore(ref global::AvroSharp.IO.AvroWriter writer, Event value, int depth)
        {
            if (depth > global::AvroSharp.Serialization.AvroGeneratedCode.MaxDepth)
            {
                throw global::AvroSharp.Serialization.AvroGeneratedCode.WriteTooDeep();
            }

            writer.WriteLong(value.Id);

            writer.WriteEnum(global::AvroSharp.Serialization.AvroGeneratedCode.CheckEnumOrdinal((int)value.Kind, 2, "app.events.Event.kind"));

            writer.WriteFixed((value.Hash ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.NullValue("app.events.Event.hash")).Value);

            global::AvroSharp.Serialization.AvroGeneratedCode.WriteList<string, global::AvroSharp.Serialization.AvroStringCodec>(ref writer, value.Tags, "app.events.Event.tags", depth + 1);

            global::AvroSharp.Serialization.AvroGeneratedCode.WriteMap<double, global::AvroSharp.Serialization.AvroDoubleCodec>(ref writer, value.Scores, "app.events.Event.scores", depth + 1);

            global::AvroSharp.Serialization.AvroGeneratedCode.WriteNullable<global::app.events.Event, global::app.events.Event.AvroCodec>(ref writer, value.Parent, 1, depth + 1);

            switch (value.Payload)
            {
                case null:
                    writer.WriteUnionIndex(0);
                    break;
                case int value0_1:
                    writer.WriteUnionIndex(1);
                    writer.WriteInt(value0_1);
                    break;
                case string value0_2:
                    writer.WriteUnionIndex(2);
                    writer.WriteString(value0_2);
                    break;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.UnionValueMismatch(value.Payload, "app.events.Event.payload");
            }
        }

        /// <summary>Reads a value into <paramref name="reuse"/> (its collections and records are filled again), or into a new instance.</summary>
        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static Event ReadCore(ref global::AvroSharp.IO.AvroReader reader, Event? reuse, int depth)
        {
            if (depth > global::AvroSharp.Serialization.AvroGeneratedCode.MaxDepth)
            {
                throw global::AvroSharp.Serialization.AvroGeneratedCode.ReadTooDeep();
            }

            var value = reuse ?? new Event(default(global::AvroSharp.Serialization.AvroUninitialized));
            value.Id = reader.ReadLong();
            value.Kind = (global::app.events.Kind)global::AvroSharp.Serialization.AvroGeneratedCode.ReadEnumOrdinal(ref reader, 2, "app.events.Kind");
            value.Hash = new global::app.events.Hash(global::AvroSharp.Serialization.AvroGeneratedCode.ReadFixedBytes(ref reader, 2));
            value.Tags = global::AvroSharp.Serialization.AvroGeneratedCode.ReadList<string, global::AvroSharp.Serialization.AvroStringCodec>(ref reader, value.Tags, 1, depth + 1);
            value.Scores = global::AvroSharp.Serialization.AvroGeneratedCode.ReadMap<double, global::AvroSharp.Serialization.AvroDoubleCodec>(ref reader, value.Scores, 9, depth + 1);
            value.Parent = global::AvroSharp.Serialization.AvroGeneratedCode.ReadNullable<global::app.events.Event, global::app.events.Event.AvroCodec>(ref reader, 1, depth + 1);
            var index1 = reader.ReadUnionIndex();
            switch (index1)
            {
                case 0:
                    value.Payload = null;
                    break;
                case 1:
                    value.Payload = reader.ReadInt();
                    break;
                case 2:
                    value.Payload = reader.ReadString();
                    break;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidUnionIndex(index1, 3);
            }
            return value;
        }

        [global::System.Diagnostics.DebuggerNonUserCode]
        internal static Event ReadResolved(ref global::AvroSharp.IO.AvroReader reader, global::AvroSharp.Serialization.AvroRecordPlan plan, int depth)
        {
            if (depth > global::AvroSharp.Serialization.AvroGeneratedCode.MaxDepth)
            {
                throw global::AvroSharp.Serialization.AvroGeneratedCode.ReadTooDeep();
            }

            var value = new Event(default(global::AvroSharp.Serialization.AvroUninitialized));
            for (var step = 0; step < plan.StepCount; step++)
            {
                var target = plan.Target(step, out var conversion);
                if (target < 0)
                {
                    plan.Skip(step, ref reader);
                }
                else if (conversion == global::AvroSharp.Serialization.AvroConversion.None)
                {
                    ReadField(ref reader, value, target, depth);
                }
                else if (!ReadPromoted(ref reader, value, target, conversion, plan, step))
                {
                    var field = new global::AvroSharp.IO.AvroReader(plan.Transcode(step, ref reader));
                    ReadField(ref field, value, target, depth);
                }
            }

            for (var index = 0; index < plan.DefaultCount; index++)
            {
                var field = new global::AvroSharp.IO.AvroReader(plan.DefaultValue(index));
                ReadField(ref field, value, plan.DefaultTarget(index), depth);
            }

            return value;
        }

        [global::System.Diagnostics.DebuggerNonUserCode]
        private static void ReadField(ref global::AvroSharp.IO.AvroReader reader, Event value, int field, int depth)
        {
            switch (field)
            {
                case 0:
                    value.Id = reader.ReadLong();
                    break;
                case 1:
                    value.Kind = (global::app.events.Kind)global::AvroSharp.Serialization.AvroGeneratedCode.ReadEnumOrdinal(ref reader, 2, "app.events.Kind");
                    break;
                case 2:
                    value.Hash = new global::app.events.Hash(global::AvroSharp.Serialization.AvroGeneratedCode.ReadFixedBytes(ref reader, 2));
                    break;
                case 3:
                    value.Tags = global::AvroSharp.Serialization.AvroGeneratedCode.ReadList<string, global::AvroSharp.Serialization.AvroStringCodec>(ref reader, null, 1, depth + 1);
                    break;
                case 4:
                    value.Scores = global::AvroSharp.Serialization.AvroGeneratedCode.ReadMap<double, global::AvroSharp.Serialization.AvroDoubleCodec>(ref reader, null, 9, depth + 1);
                    break;
                case 5:
                    value.Parent = global::AvroSharp.Serialization.AvroGeneratedCode.ReadNullable<global::app.events.Event, global::app.events.Event.AvroCodec>(ref reader, 1, depth + 1);
                    break;
                case 6:
                    var index2 = reader.ReadUnionIndex();
                    switch (index2)
                    {
                        case 0:
                            value.Payload = null;
                            break;
                        case 1:
                            value.Payload = reader.ReadInt();
                            break;
                        case 2:
                            value.Payload = reader.ReadString();
                            break;
                        default:
                            throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidUnionIndex(index2, 3);
                    }
                    break;
            }
        }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [global::System.Diagnostics.DebuggerNonUserCode]
        private static bool ReadPromoted(ref global::AvroSharp.IO.AvroReader reader, Event value, int field, global::AvroSharp.Serialization.AvroConversion conversion, global::AvroSharp.Serialization.AvroRecordPlan plan, int step)
        {
            switch (field)
            {
                case 0:
                    switch (conversion)
                    {
                        case global::AvroSharp.Serialization.AvroConversion.FromInt:
                            value.Id = reader.ReadInt();
                            return true;
                    }
                    break;
                case 1:
                    switch (conversion)
                    {
                        case global::AvroSharp.Serialization.AvroConversion.EnumRemap:
                            value.Kind = (global::app.events.Kind)plan.MapEnum(step, reader.ReadEnum());
                            return true;
                    }
                    break;
            }

            return false;
        }
    }
}
