// <auto-generated/>
// Generated by AvroSharp.CodeGen from the Avro schema of 'app.events.Kind'. Do not edit.
#nullable enable
#pragma warning disable CS1591 // Members without an Avro doc have no documentation comment.

namespace app.events
{
    [global::System.CodeDom.Compiler.GeneratedCode("AvroSharp.CodeGen", "0.0.0.0")]
    public enum Kind
    {
        CREATED = 0,
        DELETED = 1,
    }
}
