// <auto-generated/>
// Generated by AvroSharp.CodeGen from the Avro schema of 'app.events.Hash'. Do not edit.
#nullable enable
#pragma warning disable CS1591, CS8981

namespace app.events
{
    [global::System.CodeDom.Compiler.GeneratedCode("AvroSharp.CodeGen", "<version>")]
    public sealed partial class Hash : global::System.IEquatable<Hash>
    {
        /// <summary>The number of bytes in a value.</summary>
        public const int Size = 2;

        private static global::AvroSharp.Schemas.AvroSchema? s_schema;

        /// <summary>The Avro schema of this type, as JSON.</summary>
        public const string SchemaJson =
            "{\"type\":\"fixed\",\"name\":\"Hash\",\"namespace\":\"app.events\",\"size\":2}";

        /// <summary>Gets the Avro schema of this type.</summary>
        public static global::AvroSharp.Schemas.AvroSchema Schema => s_schema ?? global::AvroSharp.Serialization.AvroGeneratedCode.PublishSchema(ref s_schema, global::AvroSharp.Schemas.AvroSchema.Parse(SchemaJson));

        /// <summary>Creates a value from exactly <see cref="Size"/> bytes. The array is not copied.</summary>
        public Hash(byte[] value)
        {
            Value = global::AvroSharp.Serialization.AvroGeneratedCode.CheckFixedSize(value, Size, "app.events.Hash");
        }

        /// <summary>Gets the bytes.</summary>
        public byte[] Value { get; }

        /// <inheritdoc />
        public bool Equals(Hash? other) => !(other is null) && global::System.MemoryExtensions.SequenceEqual(new global::System.ReadOnlySpan<byte>(Value), other.Value);

        /// <inheritdoc />
        public override bool Equals(object? obj) => obj is Hash other && Equals(other);

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hash = -2128831035;
            foreach (var b in Value)
            {
                hash = (hash ^ b) * 16777619;
            }

            return hash;
        }

        /// <summary>Gets the bytes as a read-only span.</summary>
        public global::System.ReadOnlySpan<byte> AsSpan() => Value;

        /// <summary>Compares two values by their bytes.</summary>
        public static bool operator ==(Hash? left, Hash? right) => left is null ? right is null : left.Equals(right);

        /// <summary>Compares two values by their bytes.</summary>
        public static bool operator !=(Hash? left, Hash? right) => !(left == right);
    }
}
