// <auto-generated/>
// Generated by AvroSharp.CodeGen from the Avro schema of 'app.events.Event'. Do not edit.
#nullable enable
#pragma warning disable CS1591 // Members without an Avro doc have no documentation comment.

namespace app.events
{
    /// <summary>
    /// Something that happened.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("AvroSharp.CodeGen", "0.0.0.0")]
    public sealed partial class Event : global::AvroSharp.Serialization.IAvroSpecificRecord
    {
        /// <summary>The Avro schema of this type, as JSON.</summary>
        public const string SchemaJson = "{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"app.events\",\"doc\":\"Something that happened.\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"kind\",\"type\":{\"type\":\"enum\",\"name\":\"Kind\",\"symbols\":[\"CREATED\",\"DELETED\"]}},{\"name\":\"hash\",\"type\":{\"type\":\"fixed\",\"name\":\"Hash\",\"size\":2}},{\"name\":\"tags\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"scores\",\"type\":{\"type\":\"map\",\"values\":\"double\"}},{\"name\":\"parent\",\"type\":[\"null\",\"Event\"]},{\"name\":\"payload\",\"type\":[\"null\",\"int\",\"string\"]}]}";

        private static global::AvroSharp.Schemas.AvroSchema? s_schema;

        /// <summary>Gets the Avro schema of this type.</summary>
        public static global::AvroSharp.Schemas.AvroSchema Schema => s_schema ?? (s_schema = global::AvroSharp.Schemas.AvroSchema.Parse(SchemaJson));

        public long Id { get; set; }

        public global::app.events.Kind Kind { get; set; }

        public global::app.events.Hash Hash { get; set; } = null!;

        public global::System.Collections.Generic.List<string> Tags { get; set; } = new global::System.Collections.Generic.List<string>();

        public global::System.Collections.Generic.Dictionary<string, double> Scores { get; set; } = new global::System.Collections.Generic.Dictionary<string, double>();

        public global::app.events.Event? Parent { get; set; }

        public object? Payload { get; set; }

        /// <summary>Writes a value in Avro binary encoding.</summary>
        public static void Write(ref global::AvroSharp.IO.AvroWriter writer, Event value)
        {
            if (value is null)
            {
                throw new global::System.ArgumentNullException(nameof(value));
            }

            WriteCore(ref writer, value, 0);
        }

        /// <summary>Reads a value written with this type's schema.</summary>
        public static Event Read(ref global::AvroSharp.IO.AvroReader reader) => ReadCore(ref reader, 0);

        /// <summary>Writes this value to a new array, in Avro binary encoding.</summary>
        public byte[] ToAvroBytes() => global::AvroSharp.Serialization.AvroGeneratedCode.SerializeToArray(this, Write);

        /// <summary>Reads a value from Avro binary data written with this type's schema.</summary>
        public static Event FromAvroBytes(global::System.ReadOnlySpan<byte> data)
        {
            var reader = new global::AvroSharp.IO.AvroReader(data);
            return ReadCore(ref reader, 0);
        }

        /// <summary>
        /// Reads a value written with <paramref name="writerSchema"/>, another version of this type's schema, resolving the
        /// differences as the specification allows (added fields take their defaults, removed fields are skipped, numbers
        /// are promoted). Data written with this type's own schema is read directly.
        /// </summary>
        public static Event Read(ref global::AvroSharp.IO.AvroReader reader, global::AvroSharp.Schemas.AvroSchema writerSchema)
        {
            if (global::AvroSharp.Serialization.AvroGeneratedCode.IsSameSchema(writerSchema, Schema))
            {
                return ReadCore(ref reader, 0);
            }

            var plan = global::AvroSharp.Serialization.AvroGeneratedCode.GetRecordPlan(writerSchema, Schema);
            if (plan != null)
            {
                return ReadResolved(ref reader, plan, 0);
            }

            return FromAvroBytes(global::AvroSharp.Serialization.AvroGeneratedCode.ResolveToReaderEncoding(ref reader, writerSchema, Schema));
        }

        /// <summary>Reads a value from Avro binary data written with <paramref name="writerSchema"/>, resolving schema differences.</summary>
        public static Event FromAvroBytes(global::System.ReadOnlySpan<byte> data, global::AvroSharp.Schemas.AvroSchema writerSchema)
        {
            var reader = new global::AvroSharp.IO.AvroReader(data);
            return Read(ref reader, writerSchema);
        }

        global::AvroSharp.Schemas.RecordSchema global::AvroSharp.Serialization.IAvroSpecificRecord.Schema => (global::AvroSharp.Schemas.RecordSchema)Schema;

        /// <summary>Gets the value of the field at a position in the schema, boxed.</summary>
        public object? Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0:
                    return this.Id;
                case 1:
                    return this.Kind;
                case 2:
                    return this.Hash;
                case 3:
                    return this.Tags;
                case 4:
                    return this.Scores;
                case 5:
                    return this.Parent;
                case 6:
                    return this.Payload;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidFieldPosition(fieldPos, 7, "app.events.Event");
            }
        }

        /// <summary>Sets the value of the field at a position in the schema; the value must have the field's C# type.</summary>
        public void Put(int fieldPos, object? fieldValue)
        {
            switch (fieldPos)
            {
                case 0:
                    this.Id = fieldValue is long v0 ? v0 : throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, "app.events.Event.id", "long");
                    break;
                case 1:
                    this.Kind = fieldValue is global::app.events.Kind v1 ? v1 : throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, "app.events.Event.kind", "app.events.Kind");
                    break;
                case 2:
                    this.Hash = fieldValue as global::app.events.Hash ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, "app.events.Event.hash", "app.events.Hash");
                    break;
                case 3:
                    this.Tags = fieldValue as global::System.Collections.Generic.List<string> ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, "app.events.Event.tags", "System.Collections.Generic.List<string>");
                    break;
                case 4:
                    this.Scores = fieldValue as global::System.Collections.Generic.Dictionary<string, double> ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, "app.events.Event.scores", "System.Collections.Generic.Dictionary<string, double>");
                    break;
                case 5:
                    this.Parent = fieldValue == null ? (global::app.events.Event?)null : fieldValue as global::app.events.Event ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.PutTypeMismatch(fieldValue, "app.events.Event.parent", "app.events.Event?");
                    break;
                case 6:
                    this.Payload = fieldValue;
                    break;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidFieldPosition(fieldPos, 7, "app.events.Event");
            }
        }

        internal static void WriteCore(ref global::AvroSharp.IO.AvroWriter writer, Event value, int depth)
        {
            if (depth > global::AvroSharp.Serialization.AvroGeneratedCode.MaxDepth)
            {
                throw global::AvroSharp.Serialization.AvroGeneratedCode.WriteTooDeep();
            }

            writer.WriteLong(value.Id);

            writer.WriteEnum((int)value.Kind);

            writer.WriteFixed((value.Hash ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.NullValue("app.events.Event.hash")).Value);

            {
                var items0 = (value.Tags ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.NullValue("app.events.Event.tags"));
                if (items0.Count > 0)
                {
                    writer.WriteBlockCount(items0.Count);
#if NET8_0_OR_GREATER
                    foreach (var item0 in global::System.Runtime.InteropServices.CollectionsMarshal.AsSpan(items0))
#else
                    foreach (var item0 in items0)
#endif
                    {
                        writer.WriteString((item0 ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.NullValue("app.events.Event.tags")));
                    }
                }
                writer.WriteBlockEnd();
            }

            {
                var map1 = (value.Scores ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.NullValue("app.events.Event.scores"));
                if (map1.Count > 0)
                {
                    writer.WriteBlockCount(map1.Count);
                    foreach (var entry1 in map1)
                    {
                        writer.WriteString(entry1.Key);
                        writer.WriteDouble(entry1.Value);
                    }
                }
                writer.WriteBlockEnd();
            }

            if (value.Parent is global::app.events.Event value2)
            {
                writer.WriteUnionIndex(1);
                global::app.events.Event.WriteCore(ref writer, (value2 ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.NullValue("app.events.Event.parent")), depth + 1);
            }
            else
            {
                writer.WriteUnionIndex(0);
            }

            switch (value.Payload)
            {
                case null:
                    writer.WriteUnionIndex(0);
                    break;
                case int value3_1:
                    writer.WriteUnionIndex(1);
                    writer.WriteInt(value3_1);
                    break;
                case string value3_2:
                    writer.WriteUnionIndex(2);
                    writer.WriteString((value3_2 ?? throw global::AvroSharp.Serialization.AvroGeneratedCode.NullValue("app.events.Event.payload")));
                    break;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.UnionValueMismatch(value.Payload, "app.events.Event.payload");
            }
        }

        internal static Event ReadCore(ref global::AvroSharp.IO.AvroReader reader, int depth)
        {
            if (depth > global::AvroSharp.Serialization.AvroGeneratedCode.MaxDepth)
            {
                throw global::AvroSharp.Serialization.AvroGeneratedCode.ReadTooDeep();
            }

            var value = new Event();
            value.Id = reader.ReadLong();
            value.Kind = (global::app.events.Kind)global::AvroSharp.Serialization.AvroGeneratedCode.ReadEnumOrdinal(ref reader, 2, "app.events.Kind");
            value.Hash = new global::app.events.Hash(reader.ReadFixedSpan(2).ToArray());
            {
                var items4 = new global::System.Collections.Generic.List<string>();
                int count4;
                while ((count4 = global::AvroSharp.Serialization.AvroGeneratedCode.ReadBlockItemCount(ref reader, 1, items4.Count)) != 0)
                {
                    if (items4.Count == 0)
                    {
                        items4.Capacity = global::AvroSharp.Serialization.AvroGeneratedCode.InitialCapacity(count4);
                    }
                    for (var i4 = 0; i4 < count4; i4++)
                    {
                        string item4;
                        item4 = reader.ReadString();
                        items4.Add(item4);
                    }
                }
                value.Tags = items4;
            }
            {
                var count5 = global::AvroSharp.Serialization.AvroGeneratedCode.ReadBlockItemCount(ref reader, 9, 0);
                var map5 = new global::System.Collections.Generic.Dictionary<string, double>(global::AvroSharp.Serialization.AvroGeneratedCode.InitialCapacity(count5), global::System.StringComparer.Ordinal);
                while (count5 != 0)
                {
                    for (var i5 = 0; i5 < count5; i5++)
                    {
                        var key5 = reader.ReadString();
                        double value5;
                        value5 = reader.ReadDouble();
                        map5[key5] = value5;
                    }
                    count5 = global::AvroSharp.Serialization.AvroGeneratedCode.ReadBlockItemCount(ref reader, 9, map5.Count);
                }
                value.Scores = map5;
            }
            var index6 = reader.ReadUnionIndex();
            switch (index6)
            {
                case 0:
                    value.Parent = null;
                    break;
                case 1:
                    value.Parent = global::app.events.Event.ReadCore(ref reader, depth + 1);
                    break;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidUnionIndex(index6, 2);
            }
            var index7 = reader.ReadUnionIndex();
            switch (index7)
            {
                case 0:
                    value.Payload = null;
                    break;
                case 1:
                    value.Payload = reader.ReadInt();
                    break;
                case 2:
                    value.Payload = reader.ReadString();
                    break;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidUnionIndex(index7, 3);
            }
            return value;
        }

        internal static Event ReadResolved(ref global::AvroSharp.IO.AvroReader reader, global::AvroSharp.Serialization.AvroRecordPlan plan, int depth)
        {
            if (depth > global::AvroSharp.Serialization.AvroGeneratedCode.MaxDepth)
            {
                throw global::AvroSharp.Serialization.AvroGeneratedCode.ReadTooDeep();
            }

            var value = new Event();
            for (var step = 0; step < plan.StepCount; step++)
            {
                switch (plan.Target(step))
                {
                    case 0:
                        switch (plan.Conversion(step))
                        {
                            case global::AvroSharp.Serialization.AvroConversion.None:
                                value.Id = ReadResolvedField0(ref reader, depth);
                                break;
                            case global::AvroSharp.Serialization.AvroConversion.FromInt:
                                value.Id = reader.ReadInt();
                                break;
                            default:
                                {
                                    var field = new global::AvroSharp.IO.AvroReader(plan.Transcode(step, ref reader));
                                    value.Id = ReadResolvedField0(ref field, depth);
                                    break;
                                }
                        }
                        break;
                    case 1:
                        switch (plan.Conversion(step))
                        {
                            case global::AvroSharp.Serialization.AvroConversion.None:
                                value.Kind = ReadResolvedField1(ref reader, depth);
                                break;
                            case global::AvroSharp.Serialization.AvroConversion.EnumRemap:
                                value.Kind = (global::app.events.Kind)plan.MapEnum(step, reader.ReadEnum());
                                break;
                            default:
                                {
                                    var field = new global::AvroSharp.IO.AvroReader(plan.Transcode(step, ref reader));
                                    value.Kind = ReadResolvedField1(ref field, depth);
                                    break;
                                }
                        }
                        break;
                    case 2:
                        switch (plan.Conversion(step))
                        {
                            case global::AvroSharp.Serialization.AvroConversion.None:
                                value.Hash = ReadResolvedField2(ref reader, depth);
                                break;
                            default:
                                {
                                    var field = new global::AvroSharp.IO.AvroReader(plan.Transcode(step, ref reader));
                                    value.Hash = ReadResolvedField2(ref field, depth);
                                    break;
                                }
                        }
                        break;
                    case 3:
                        switch (plan.Conversion(step))
                        {
                            case global::AvroSharp.Serialization.AvroConversion.None:
                                value.Tags = ReadResolvedField3(ref reader, depth);
                                break;
                            default:
                                {
                                    var field = new global::AvroSharp.IO.AvroReader(plan.Transcode(step, ref reader));
                                    value.Tags = ReadResolvedField3(ref field, depth);
                                    break;
                                }
                        }
                        break;
                    case 4:
                        switch (plan.Conversion(step))
                        {
                            case global::AvroSharp.Serialization.AvroConversion.None:
                                value.Scores = ReadResolvedField4(ref reader, depth);
                                break;
                            default:
                                {
                                    var field = new global::AvroSharp.IO.AvroReader(plan.Transcode(step, ref reader));
                                    value.Scores = ReadResolvedField4(ref field, depth);
                                    break;
                                }
                        }
                        break;
                    case 5:
                        switch (plan.Conversion(step))
                        {
                            case global::AvroSharp.Serialization.AvroConversion.None:
                                value.Parent = ReadResolvedField5(ref reader, depth);
                                break;
                            default:
                                {
                                    var field = new global::AvroSharp.IO.AvroReader(plan.Transcode(step, ref reader));
                                    value.Parent = ReadResolvedField5(ref field, depth);
                                    break;
                                }
                        }
                        break;
                    case 6:
                        switch (plan.Conversion(step))
                        {
                            case global::AvroSharp.Serialization.AvroConversion.None:
                                value.Payload = ReadResolvedField6(ref reader, depth);
                                break;
                            default:
                                {
                                    var field = new global::AvroSharp.IO.AvroReader(plan.Transcode(step, ref reader));
                                    value.Payload = ReadResolvedField6(ref field, depth);
                                    break;
                                }
                        }
                        break;
                    default:
                        plan.Skip(step, ref reader);
                        break;
                }
            }

            for (var index = 0; index < plan.DefaultCount; index++)
            {
                var field = new global::AvroSharp.IO.AvroReader(plan.DefaultValue(index));
                switch (plan.DefaultTarget(index))
                {
                    case 0:
                        value.Id = ReadResolvedField0(ref field, depth);
                        break;
                    case 1:
                        value.Kind = ReadResolvedField1(ref field, depth);
                        break;
                    case 2:
                        value.Hash = ReadResolvedField2(ref field, depth);
                        break;
                    case 3:
                        value.Tags = ReadResolvedField3(ref field, depth);
                        break;
                    case 4:
                        value.Scores = ReadResolvedField4(ref field, depth);
                        break;
                    case 5:
                        value.Parent = ReadResolvedField5(ref field, depth);
                        break;
                    case 6:
                        value.Payload = ReadResolvedField6(ref field, depth);
                        break;
                }
            }

            return value;
        }

        private static long ReadResolvedField0(ref global::AvroSharp.IO.AvroReader reader, int depth)
        {
            long result;
            result = reader.ReadLong();
            return result;
        }

        private static global::app.events.Kind ReadResolvedField1(ref global::AvroSharp.IO.AvroReader reader, int depth)
        {
            global::app.events.Kind result;
            result = (global::app.events.Kind)global::AvroSharp.Serialization.AvroGeneratedCode.ReadEnumOrdinal(ref reader, 2, "app.events.Kind");
            return result;
        }

        private static global::app.events.Hash ReadResolvedField2(ref global::AvroSharp.IO.AvroReader reader, int depth)
        {
            global::app.events.Hash result;
            result = new global::app.events.Hash(reader.ReadFixedSpan(2).ToArray());
            return result;
        }

        private static global::System.Collections.Generic.List<string> ReadResolvedField3(ref global::AvroSharp.IO.AvroReader reader, int depth)
        {
            global::System.Collections.Generic.List<string> result;
            {
                var items8 = new global::System.Collections.Generic.List<string>();
                int count8;
                while ((count8 = global::AvroSharp.Serialization.AvroGeneratedCode.ReadBlockItemCount(ref reader, 1, items8.Count)) != 0)
                {
                    if (items8.Count == 0)
                    {
                        items8.Capacity = global::AvroSharp.Serialization.AvroGeneratedCode.InitialCapacity(count8);
                    }
                    for (var i8 = 0; i8 < count8; i8++)
                    {
                        string item8;
                        item8 = reader.ReadString();
                        items8.Add(item8);
                    }
                }
                result = items8;
            }
            return result;
        }

        private static global::System.Collections.Generic.Dictionary<string, double> ReadResolvedField4(ref global::AvroSharp.IO.AvroReader reader, int depth)
        {
            global::System.Collections.Generic.Dictionary<string, double> result;
            {
                var count9 = global::AvroSharp.Serialization.AvroGeneratedCode.ReadBlockItemCount(ref reader, 9, 0);
                var map9 = new global::System.Collections.Generic.Dictionary<string, double>(global::AvroSharp.Serialization.AvroGeneratedCode.InitialCapacity(count9), global::System.StringComparer.Ordinal);
                while (count9 != 0)
                {
                    for (var i9 = 0; i9 < count9; i9++)
                    {
                        var key9 = reader.ReadString();
                        double value9;
                        value9 = reader.ReadDouble();
                        map9[key9] = value9;
                    }
                    count9 = global::AvroSharp.Serialization.AvroGeneratedCode.ReadBlockItemCount(ref reader, 9, map9.Count);
                }
                result = map9;
            }
            return result;
        }

        private static global::app.events.Event? ReadResolvedField5(ref global::AvroSharp.IO.AvroReader reader, int depth)
        {
            global::app.events.Event? result;
            var index10 = reader.ReadUnionIndex();
            switch (index10)
            {
                case 0:
                    result = null;
                    break;
                case 1:
                    result = global::app.events.Event.ReadCore(ref reader, depth + 1);
                    break;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidUnionIndex(index10, 2);
            }
            return result;
        }

        private static object? ReadResolvedField6(ref global::AvroSharp.IO.AvroReader reader, int depth)
        {
            object? result;
            var index11 = reader.ReadUnionIndex();
            switch (index11)
            {
                case 0:
                    result = null;
                    break;
                case 1:
                    result = reader.ReadInt();
                    break;
                case 2:
                    result = reader.ReadString();
                    break;
                default:
                    throw global::AvroSharp.Serialization.AvroGeneratedCode.InvalidUnionIndex(index11, 3);
            }
            return result;
        }
    }
}
