// <auto-generated/>
// Generated by AvroSharp.CodeGen from the Avro schema of 'app.events.Kind'. Do not edit.
#nullable enable
#pragma warning disable CS1591, CS8981

namespace app.events
{
    [global::System.CodeDom.Compiler.GeneratedCode("AvroSharp.CodeGen", "<version>")]
    public enum Kind
    {
        CREATED = 0,
        DELETED = 1,
    }
}
